### PR TITLE
UIResponder become/resign bindings

### PR DESCRIPTION
**Pull request by hernangonzalez**
Hello!

Does this look OK? I am not very experienced and was in need of a binding here. Let me know if this is good enough and I will add tests to it.

Thank you!
Hernán

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @hernangonzalez ,

hm ... Could you maybe provide some context to this? I didn't need those extensions, so I'm little curious about how do you use them, and in what cases.

**Comment by hernangonzalez** [comment]
hi @kzaher I used this to connect actions of UI items still visible that would end up in actions that i want to dismiss the keyboard to. I.e if a user taps Done on the keyboard:
```
		/**
		Search is handled dynamically as user tipes. So we use the return key
		as done and dismiss the keyboard instead.
		*/
		searchBar.rx_searchButtonClicked
			.asDriver()
			.drive(searchBar.rx_resignFirstResponder)
			.addDisposableTo(rx_disposeBag)
```

**Comment by kzaher** [comment]
Hey @hernangonzalez ,

I've been thinking about this. I think this is part of a more general problem, how do you bind '()' to call any method. If we were to add this extension, this would open doors to a bunch of extensions we could add :). There is a lot of methods out there, and all could potentially be event targets.

I think your code could be rewritten as:

```swift
searchBar.rx_searchButtonClicked
            .asDriver()
            .drive(weakify(searchBar, searchBar.dynamicType.resignFirstResponder))
            .addDisposableTo(rx_disposeBag)
```

It's not significantly longer, and there is a lot of weakify libraries out there :)

¯\\\_(ツ)\_/¯ 

I totally agree your extension is useful, and more readable then my suggestion, but not sure it would be a good idea to start pulling in similar extensions because this library would bloat too much.

**Comment by hernangonzalez** [comment]
Sure @kzaher, I agree that is best to try and keep the lib slim. I'll give a shot to the weakify frameworks (just found https://github.com/klundberg/Weakify), and ping back if its not working for me.

Thanks,
H.

**Comment by serejahh** [comment]
Hi @hernangonzalez 
You can create a PR with your changes here: https://github.com/RxSwiftCommunity/RxSwiftExt/

**Comment by hernangonzalez** [comment]
Hi @serejahh will do that, thank you.

**Pull request closed without merging**
