### PR TITLE
Add Swift 3 swift-DEVELOPMENT-SNAPSHOT-2016-05-09 compatibility.

### PR DESCRIPTION
**Pull request by TheArtOfEngineering**
Added swift-DEVELOPMENT-SNAPSHOT-2016-05-09 compatibility. These changes included reordering @noescape, wrapping the parameter of single parameter function types with parentheses, conforming to the new index APIs, and implicitly unwrapping newly annotated libdispatch functions.

All additions of IUOs have been marked with // Swift 3.0 IUO.

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @TheArtOfEngineering ,

you changes look ok, but I'm having problems validating them. Could you please tell me where does this work for you?

I've tried using Linux toolchain and it failed.
I've tried using Xcode, but Xcode crashes immediately when I open it. (yes I've tried cleaning derived data, deleting project files, reinstalling xcode and toolchains, but xcode just crashes at startup). 
I've tried using terminal in osx, but couldn't get xcodebuild to work with latest toolchain.

**Comment by TheArtOfEngineering** [comment]
Hi @kzaher,

I built in on OS X using the swift-DEVELOPMENT-SNAPSHOT-2016-05-09 toolchain. I edited the file by opening the .xcodeproj in Xcode. Perhaps it has something to do with fact that I used the xcodeproj rather than the workspace? I can pull out the change to the Rx.xcscmblueprint and to see if that fixes the issue.

What was the failure with the Linux toolchain?

**Comment by TheArtOfEngineering** [comment]
I've removed the Rx.xcscmblueprint, squashed all the commits, and confirmed that it builds with swift-DEVELOPMENT-SNAPSHOT-2016-05-09.

**Comment by kzaher** [comment]
I've tried to verify these changes, but what ever I do Swift compiler keeps crashing on me.

On the other hand, the changes look legit, so I guess I will merge them without actually being able to compile this thing, and hoping next version of toolchain will enable me to compile this.

This is nuts.

**Pull request merged**
