### PR TITLE
add Binder for backgroundColor on UIView

### PR DESCRIPTION
**Pull request by Oni-zerone**
Just a simple Binder implementation for UIView backgroundColor

### CODE REVIEW

**Comment by freak4pc** [comment]
Usually we don't add trivial Binders to RxCocoa core, but in this case, I think `backgroundColor` is a common enough UIView thing to be added. It's still quite trivial for a codebase to add themselves, so I'm not sure if it's quite needed. 

@kzaher WDYT ?

**Comment by kzaher** [comment]
@freak4pc I agree that this is common enough. 

@Oni-zerone 
Let's just add tests for this.

**Comment by Oni-zerone** [comment]
I'm sorry I was working on the tests, thanks @freak4pc for your support

**Comment by freak4pc** [comment]
Hey @Oni-zerone ! Sorry, just wanted to make sure this is added to the upcoming release, hope it didn't feel as if I'm messing with your PR :)

**Comment by Oni-zerone** [comment]
@freak4pc Don't worry, it was just a little change that I've requested and I did not want to ask others to do it for me :)

**Comment by freak4pc** [comment]
I've also added a CHANGELOG entry (and added some that we forgot in some other PRs that were merged lately 🙄)

**Comment by freak4pc** [comment]
Test failures seem unrelated, trying again here. 

> unexpected service error: The Xcode build system has crashed. Please close and reopen your workspace.

**Pull request merged**
