### PR TITLE
Add final keyworks to all posibles classes

### PR DESCRIPTION
**Pull request by carlosypunto**
Relating to #1057 issue. 
[WIP] Mass work done. Maybe all public classes shouldn't be final (fast and easy find and manual replace) and is posible for some non final classes to make some method final.
Happy new year @kzaher 🙂

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @carlosypunto ,

Looks like CI is failing. https://travis-ci.org/ReactiveX/RxSwift/jobs/189486522

**Comment by carlosypunto** [comment]
Hi @kzaher,
CI is not passing because Danger script don't pass:

```bash
The command "if [[ "${DANGER}" -eq 1 ]] ; then bundle install --path vendor/bundle; bundle exec danger --verbose; else if [[ `uname` == "Darwin" ]] ; then xcodebuild -version; xcodebuild -showsdks; fi; TRAVIS=1 ./scripts/all-tests.sh "${TEST}"; fi" exited with 1.
```

**Comment by carlosypunto** [comment]
@kzaher all-tests.sh is passing correctly

**Comment by carlosypunto** [comment]
@kzaher Oh no, other thinks are broken. I will check now

**Comment by carlosypunto** [comment]
All test in CI are passing now.
All `open` classes aren't `final` but public ones are `final`. @kzaher, maybe you want we set some `public` methods of open ones will be `final` keyword too.

**Pull request merged**
