### PR TITLE
Add rx.isHighlighted to UIImageView

### PR DESCRIPTION
**Pull request by ThomasLeblond**
Add rx.isHighlighted to UIImageView

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @ThomasLeblond ,

Hm. I think that if we add this, we would need to add highlighted image, etc. I'm not sure a lot of people use it, or know about this.

**Comment by ThomasLeblond** [comment]
Hi @kzaher,

It's really useful when you want a check image for a form.

```swift
let emailValid = emailTextField.rx.text.orEmpty
            .map { !$0.isEmpty && $0.isMatch(RegexPattern.email) }
            .shareReplay(1)

emailValid
            .bind(to: emailImageView.rx.isHighlighted)
            .disposed(by: disposeBag)
```

**Comment by sergdort** [comment]
I agree with @kzaher 
This is fairly simple to implement. And I'm not sure if this is that common to use. TBH I've used this property couple times only

**Comment by kzaher** [comment]
Let's skip this for now then :)

**Pull request closed without merging**
