### PR TITLE
fix macos RxCocoa compilation error in Xcode 10

### PR DESCRIPTION
**Pull request by carlosypunto**
Fix reported errors reported issue #1709, retaining swift 4.0/4.2 compativility

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @carlosypunto ,

I understand that your intentions are good, but please don't merge anything without somebody taking a look at what you are doing first.

You have merged directly to master branch, which is not consistent with our workflow, and we still need to investigate what is happening and why our release tests passed.

**Comment by carlosypunto** [comment]
Sorry :-(, your right.

**Comment by carlosypunto** [comment]
@kzaher, In Xcode 10:
### `pod 'RxCocoa', git: 'https://github.com/ReactiveX/RxSwift', branch: 'master'`

        - Sample:  https://github.com/carlosypunto/TestRxSwifMacOSInXcode10ToMaster

           `xcodebuild -workspace TestRxSwifMacOSInXcode10ToMaster.xcworkspace -scheme TestRxSwifMacOSInXcode10ToMaster` returns:
```
           ** BUILD SUCCEEDED ** [0.761 sec]
```

### using:
        `pod 'RxCocoa'`

        - Sample:  https://github.com/carlosypunto/TestRxSwifMacOSInXcode10

           `xcodebuild -workspace TestRxSwifMacOSInXcode10.xcworkspace -scheme TestRxSwifMacOSInXcode10` returns:
	
```
	** BUILD FAILED **
	The following build commands failed:
		CompileSwift normal x86_64 /Users/carlos/Documents/CurreleActual/StoryboardEditor/Resources/TestRxSwifMacOSInXcode10/Pods/RxCocoa/RxCocoa/Deprecated.swift
		CompileSwift normal x86_64 /Users/carlos/Documents/CurreleActual/StoryboardEditor/Resources/TestRxSwifMacOSInXcode10/Pods/RxCocoa/RxCocoa/macOS/NSTextField+Rx.swift
		CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
```

**Comment by carlosypunto** [comment]
podspec's `s.swift-version`, file` .swift-version` or `--swift-version` affects to` pod spec lint` as `pod spec lint --swift-version`. But not affect to version setted to compile the pods't targets of a Podfile. BTW I think **RxBlockig** do not compile too

**Comment by kzaher** [comment]
Ok, cool. I'll add `pod spec lint --swift-version` to our travis CI once we get Xcode on travis.

**Comment by freak4pc** [comment]
Xcode 10 is already on Travis FYI


On Sep 19, 2018 at 09:11, Krunoslav Zaher <notifications@github.com> wrote:


Ok, cool. I'll add pod spec lint --swift-version to our travis CI once we
get Xcode on travis.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ReactiveX/RxSwift/pull/1742#issuecomment-422683470>,
or mute
the thread

**Comment by carlosypunto** [comment]
I think, `pod spec lint --swift-version=4.2` still producing version warning. In CocoaPods repo there are several issues over how to allow multiple swift versions for the same pod. `pod spec lint --swift-version` appears to will be deprecated in favor of `spec.swift_version` in __podspec__ file. I think is better to wait for they resolution.

**Comment by carlosypunto** [comment]
`spec.swift_version` as in pull #1741 sems the best solution for compilve swift versión, but I'dont know if setting it to 4.2 still working in Xcode 9.4

**Pull request merged**
