### PR TITLE
Add `TRACE_RESOURCES` to Package.swift

### PR DESCRIPTION
**Pull request by ahaubenstock**
Defines the `TRACE_RESOURCES` macro for debug builds as recommended by @danielt1263.

### CODE REVIEW

**Comment by danielt1263** [comment]
This is great. I just started using the SPM and this will come in handy.

**Comment by freak4pc** [comment]
Hey @ahaubenstock, why did you close this one?

**Comment by ahaubenstock** [comment]
@freak4p, @danielt1263 relayed to me that you said to make the pull request for the develop branch instead.

**Comment by freak4pc** [comment]
Oh ok, FYI you can also edit the base branch inside the PR :)

**Comment by ahaubenstock** [comment]
Oh darn. I looked for that capability for a couple minutes and could not find it 😁

**Pull request closed without merging**
