### PR TITLE
Update throttle of SharedSequence to support `latest` parameter

### PR DESCRIPTION
**Pull request by diogot**
The `latest` parameter is in the documentation but it's not implemented.

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @diogot ,

could you please add one more unit test analogous to `func testAsDriver_throttle()` that uses this overload.

**Comment by diogot** [comment]
Sure!

**Comment by freak4pc** [comment]
@diogot You need to run `./scripts/package-spm.swift` and commit the updated test files for the SPM Package for your tests to pass

**Comment by diogot** [comment]
Sorry, I'll do it.

**Pull request merged**
