### PR TITLE
Add Timer and Interval to Driver

### PR DESCRIPTION
**Pull request by thanegill**
Issue #455

### CODE REVIEW

**Comment by thanegill** [comment]
I can add tests if needed. I didn't see any for most of the Driver creators though.

**Comment by kzaher** [comment]
Hi @thanegill ,

I've cherry picked two commits regarding `timer` operators. Great catch there. I've really thought I've fixed that public interface when I've made element more generic, but looks like I've missed one spot.

I've also made time operator more generic, instead of having two versions of the same operator. Pushed changes to `develop` branch.

I can't pull in your commit that adds driver time functions until I refactor driver unit tests to add infrastructure to unit test time operators, and then I'll probably need to cherry-pick your third commit and change it a bit.

**Comment by thanegill** [comment]
@kzaher If it's easier I can always rebase on my end once your changes are made.

**Comment by kzaher** [comment]
I've cherry-picked part of commits and merged them 
¯\\\_(ツ)\_/¯ 
I think we can close the rest of this one.

**Comment by thanegill** [comment]
Great! Thanks @kzaher

**Pull request closed without merging**
