### PR TITLE
updated the README.md file 

### PR DESCRIPTION
**Pull request by ITHHKN**
Added short info about RxSwift ... 

"RxSwift is the reactive programming library for iOS. It makes it easy to program dynamic apps that respond to data changes and user events inside application."

### CODE REVIEW

**Comment by ITHHKN** [comment]
Added short detail and why we use it about Rxswift .

**Comment by freak4pc** [comment]
Hey @ITHHKN - I want to start off by thanking you for your effort and help, and your good will to contribute to this repo :) 

Unfortunately, I feel like this addition would not be beneficial. Aside from the various grammatical issues, the additions you added are already part of the repo. 

Intro: 

> Rx is a generic abstraction of computation expressed through Observable<Element> interface.

Why use Rx:
https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Why.md

For these reasons, I'll be closing this PR for now - but feel free to contribute other additions you see valuable.

Thanks!
Shai.

**Comment by ITHHKN** [comment]
Hi @freak4pc 

Thanks for getting back and highlighting that **why use RX** is already there , But what about the short description about the RxSwift ... **Please read below** if You think its effective and cause good impact on users for first sight . I will create new pull request ...



> RxSwift is the reactive programming library for iOS. It makes it easy to program dynamic apps that respond to data changes and user events inside application .

Thanks
H Haider

**Comment by freak4pc** [comment]
I find the definition not accurate enough. 

1. RxSwift isn't the only library for reactive programming (you have ReactiveSwift, CwlSignal, Bond, and many other implementations)
2. It is not only for iOS - it is for tvOS, Cocoa apps, watchOS and even backend services. 
3. It is not only for user-facing application. 

The best definition of it is the one we already have IMO - which is, RxSwift is the Swift implementation of the Rx standard defined by ReactiveX.io.

**Comment by ITHHKN** [comment]
@freak4pc  ... Ok i got it .... 

I will review and try to contribute.... I really wanted to be the part of this fantastic repo ... 

Thanks ...

**Comment by freak4pc** [comment]
@ITHHKN We'd love to have your contributions! Don't give up :) 
You can easily start off with some easy typos, or additions. Please just make sure that if the content you add is README related, that it is grammatically correct - english-wise ;]

**Pull request closed without merging**
