### PR TITLE
watchOS2

### PR DESCRIPTION
**Pull request by cfraz89**
A target for watchOS2

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @cfraz89 ,

I would like to merge this, but it says there is a conflict with develop. Could you please resolve it so I can merge it? :)

**Comment by cfraz89** [comment]
Sure, yeah got some issues with the xproj file I have to sort out

**Comment by kzaher** [comment]
Hi @cfraz89 ,

We are planning to release next version soon and I would really like to add watch OS support. It looks like there are some conflicts in this PR so can't merge this.

According to this, there shouldn't be any problems with watchOS in our codebase. Only targets need to be added.

I'll try to redo those changes from develop branch.

**Comment by cfraz89** [comment]
Ahhhh beat me to it. Yeah targets good to me :+1:

**Pull request closed without merging**
