### PR TITLE
Add Privacy Manifest

### PR DESCRIPTION
**Pull request by wlxo0401**
1. Added xcprivacy
- 'mach_absolute_time' exists in folder 'Tests'
- System boot time APIs - 35F9.1
- One each in the RxSwift, RxCocoa, and RxRelay folders.
- Remove If Not Required

2. Append privacy file to CocoaPods bundle
- Added to each podspec of RxSwift, RxRelay, and RxCocoa.
- I applied privacyinfo as resource_bundles.

3. SPM Package needs to be modified as well. I didn't do it because I didn't know exactly.

4. I added it by referring to other libraries. I'm sorry if the method is wrong.

5. This has not been tested. I need additional comments and validation from others.

This resolves https://github.com/ReactiveX/RxSwift/issues/2567

### CODE REVIEW

**Comment by tommyming** [comment]
Reference to the Discussion

#2567

**Comment by wlxo0401** [comment]
@tommyming 

I posted it hoping others would continue in one part. Is this also a draft?

Should I just delete PR?

I'm sorry that I'm bothering you because I'm not good at many things.

**Comment by tommyming** [comment]
It's ok @wlxo0401, asking questions is always a good thing :)

To set a PR to draft, you may check on this [Article](https://docs.github.com/ko/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request)

It is in Korean already so no worries!

**Comment by wlxo0401** [comment]
@tommyming 

Thank you, I changed this article to draft!!

**Comment by tommyming** [comment]
@wlxo0401 Please allow me to access the forked repo, or else I cannot push changes there. If you want to know how to add to SPM, please let me know, thanks.

**Comment by wlxo0401** [comment]
@tommyming 

I've invited you to join the collaborators.

Is this right?

**Comment by tommyming** [comment]
@wlxo0401 should be it, please change the PR to be review ready, thanks.
@freak4pc Please feel free to review when you have time, thanks a lot.

**Comment by wlxo0401** [comment]
@tommyming 

I changed the title and changed the state of PR to 'review-ready'.

Thank you so much for allowing me to participate in this PR process. It was a good experience for me.

**Comment by tommyming** [comment]
@wlxo0401 Please add the privacy manifest issue to this pull request:
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by wlxo0401** [comment]
fix https://github.com/ReactiveX/RxSwift/issues/2567

**Comment by wlxo0401** [comment]
> @wlxo0401 Please add the privacy manifest issue to this pull request: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

fix #2572 

like this?

**Comment by wlxo0401** [comment]
> @wlxo0401 Please add the privacy manifest issue to this pull request: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Thank you, and thanks to you, I found out about the new features. 

Check it out.

**Review by nabs-m — APPROVED** [review]
I'm not a maintainer of this repo, but I've been working with privacy manifests elsewhere so my approval is based on that.

Privacy manifest structure and reason provided matches what was mentioned [here](https://github.com/ReactiveX/RxSwift/issues/2567#issuecomment-1871093829).

All 3 additions are properly referenced in the `podspec` for each library, so privacy manifests should get imported by consuming apps as expected.

**Comment by wlxo0401** [comment]
Is it okay to do the resources path of Package.swift as it is now?

Do not have to enter an additional folder path?? 

For example, as below.
RxSwift/PrivacyInfo.xcprivacy
RxRelay/PrivacyInfo.xcprivacy

I can't read the package code well yet, so it might be a misunderstanding.

**Comment by nabs-m** [comment]
> Is it okay to do the resources path of Package.swift as it is now?
> 
> Do not have to enter an additional folder path??
> 
> For example, as below. RxSwift/PrivacyInfo.xcprivacy RxRelay/PrivacyInfo.xcprivacy
> 
> I can't read the package code well yet, so it might be a misunderstanding.

@wlxo0401 I haven't tried it myself with SPM, but I saw [this](https://github.com/airbnb/lottie-ios/pull/2252/files#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677eR22) in another open source library. Hopefully that helps?

**Comment by tommyming** [comment]
From my understanding, the privacy file will be loaded based on the path provided to SPM.
As on the file structure, the privacy manifest is on the outermost layer, so suppose we don't need to add any filePath prefixes.

Feel free to correct me if I'm wrong.

**Comment by wlxo0401** [comment]
I added PrivacyInfo and set it up because I didn't specify a target. 

I don't know if this is necessary, but please review it.

**Comment by Efebyts** [comment]
> 1. Added xcprivacy
> 
> - 'mach_absolute_time' exists in folder 'Tests'
> 
> - System boot time APIs - 35F9.1
> 
> - One each in the RxSwift, RxCocoa, and RxRelay folders.
> 
> - Remove If Not Required
> 
> 
> 
> 2. Append privacy file to CocoaPods bundle
> 
> - Added to each podspec of RxSwift, RxRelay, and RxCocoa.
> 
> - I applied privacyinfo as resource_bundles.
> 
> 
> 
> 3. SPM Package needs to be modified as well. I didn't do it because I didn't know exactly.
> 
> 
> 
> 4. I added it by referring to other libraries. I'm sorry if the method is wrong.
> 
> 
> 
> 5. This has not been tested. I need additional comments and validation from others.
> 
> 
> 
> 
> 
> This resolves https://github.com/ReactiveX/RxSwift/issues/2567

**Comment by tommyming** [comment]
@freak4pc May I know if there are any schedule for this PR? Thanks

**Comment by tommyming** [comment]
Workaround(NOT recommended):
In case you are REALLY urgent to update the framework with the privacy manifest included, you may use the fork from @wlxo0401, which is waiting to review and merge here.

Side Effects: 
Warnings will pop out in SPM when you use libraries that depend on RxSwift, as the package path conflicts with the original repo.
Although SPM won't stop you from building the target, this is not recommended as it may cause unpredictable behaviours to SPM on package path searching mechanisms.

Please feel free to correct me if anything is missing.

**Review by LongXiangGuo — APPROVED** [review]

**Comment by aiKrice** [comment]
Just an up here as a gentle reminder

**Review by ymoyao — APPROVED** [review]

**Review by freak4pc — CHANGES_REQUESTED** [review]
Hey, first of all thank you for leading this and taking this.

Unfortunately, I think this is actually incorrect.

The `mach_absolute_time` API is used in the **tests for RxSwift itself**, and not any sources that are embedded for any consumers that depend on any fo the libraries.

This repo was only flagged because it is a very popular OSS repo and some bot probably scanned this API in the GitHub repo, but there is nothing to report from a privacy perspective. 

Also, we'll need this PR to support SPM since it's the modern and popular way to consume libraries. Here's an example of how to achieve this:
https://github.com/firebase/firebase-ios-sdk/blob/fe09d61a539e11fdbe24f269bba10144b6145fe2/Package.swift#L202

Once you make the changes please ping me directly in this PR and I'll take care of a release.

Thanks!

**Comment by wlxo0401** [comment]
@freak4pc As you told me, I pushed a new Comit. 

Can I ask you to check if 'Target MemberShip' is also done properly??

I invited you to the Forked Repository just in case.

**Comment by wlxo0401** [comment]
> Hey, first of all thank you for leading this and taking this.
> 
> Unfortunately, I think this is actually incorrect.
> 
> The API is used in the **tests for RxSwift itself**, and not any sources that are embedded for any consumers that depend on any fo the libraries.`mach_absolute_time`
> 
> This repo was only flagged because it is a very popular OSS repo and some bot probably scanned this API in the GitHub repo, but there is nothing to report from a privacy perspective.
> 
> Also, we'll need this PR to support SPM since it's the modern and popular way to consume libraries. Here's an example of how to achieve this: https://github.com/firebase/firebase-ios-sdk/blob/fe09d61a539e11fdbe24f269bba10144b6145fe2/Package.swift#L202
> 
> Once you make the changes please ping me directly in this PR and I'll take care of a release.
> 
> Thanks!

@freak4pc 
As you told me, I pushed a new Comit. 

Can I ask you to check if 'Target MemberShip' is also done properly??

I invited you to the Forked Repository just in case.

-----
I would appreciate it if other people could check based on the latest content and feel free to give their opinions.

**Comment by tommyming** [comment]
> Hey, first of all thank you for leading this and taking this.
> 
> Unfortunately, I think this is actually incorrect.
> 
> The `mach_absolute_time` API is used in the **tests for RxSwift itself**, and not any sources that are embedded for any consumers that depend on any fo the libraries.
> 
> This repo was only flagged because it is a very popular OSS repo and some bot probably scanned this API in the GitHub repo, but there is nothing to report from a privacy perspective.
> 
> Also, we'll need this PR to support SPM since it's the modern and popular way to consume libraries. Here's an example of how to achieve this: https://github.com/firebase/firebase-ios-sdk/blob/fe09d61a539e11fdbe24f269bba10144b6145fe2/Package.swift#L202
> 
> Once you make the changes please ping me directly in this PR and I'll take care of a release.
> 
> Thanks!

@freak4pc thanks for the reply.

I agree that the API is used in tests only, which won't cause any privacy issues mentioned by Apple.
I guess the current approach would be to remove the test that uses it, comment it out for now, or send an inquiry to Apple.

For the SPM implementation, suppose my commit has done it. Please feel free to review the `Packaged.swift` file, in which I committed changes. 

Please feel free to tag me about SPM privacy manifest related issues.

**Comment by tommyming** [comment]
> > Hey, first of all thank you for leading this and taking this.
> > Unfortunately, I think this is actually incorrect.
> > The API is used in the **tests for RxSwift itself**, and not any sources that are embedded for any consumers that depend on any fo the libraries.`mach_absolute_time`
> > This repo was only flagged because it is a very popular OSS repo and some bot probably scanned this API in the GitHub repo, but there is nothing to report from a privacy perspective.
> > Also, we'll need this PR to support SPM since it's the modern and popular way to consume libraries. Here's an example of how to achieve this: https://github.com/firebase/firebase-ios-sdk/blob/fe09d61a539e11fdbe24f269bba10144b6145fe2/Package.swift#L202
> > Once you make the changes please ping me directly in this PR and I'll take care of a release.
> > Thanks!
> 
> @freak4pc As you told me, I pushed a new Comit.
> 
> Can I ask you to check if 'Target MemberShip' is also done properly??
> 
> I invited you to the Forked Repository just in case.
> 
> I would appreciate it if other people could check based on the latest content and feel free to give their opinions.

@wlxo0401 I guess it is not just removing the item from the privacy manifest, but also choosing the options I mentioned above.

**Comment by nabs-m** [comment]
Just want to +1 the comment around not having to report an API if it's only in tests, as it won't show up in the symbol lookup table that Apple will likely use to scan release apps. We did the same with a library we develop.

**Comment by tommyming** [comment]
Update: I have updated the SPM resource processing rules to `.process` instead of `.copy`, following `firebase-ios-sdk` practices.

@freak4pc please review when you are free, thanks.

**Review by ymoyao — APPROVED** [review]

**Review by jarrodlombardo-EventBase — APPROVED** [review]

**Comment by linhaosunny** [comment]
> 2\. CocoaPods

I 'm not use SPM, When will you support CocoaPods? When will you release the new version?

**Comment by freak4pc** [comment]
I'm closing this for now, let's continue the discussion on #2567 - 
From my current perspective RxSwift will not need to add a privacy manifest.

**Comment by linhaosunny** [comment]
> I'm closing this for now, let's continue the discussion on #2567 - From my current perspective RxSwift will not need to add a privacy manifest.

@freak4pc so that's all?

**Comment by andschdk** [comment]
@linhaosunny 
https://github.com/ReactiveX/RxSwift/issues/2567#issuecomment-2008689007

**Pull request closed without merging**
