### PR TITLE
UISegmentedControl set title and image for segment wrappers.

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Hey guys :)) 
This PR adds just two convenience wrappers to RxCocoa UISegmented Control.

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @LucianoPAlmeida ,

what is the reason to use
```swift
segmentedControl.rx.title(forSegmentAt: 0)
```
vs 
```swift
segmentedControl.titleForSegment(at: 0)
```

**Comment by LucianoPAlmeida** [comment]
Hey @kzaher :))
The use case for this one was more to set the text according to a model event. 
Something like:
```swift
// Where the textChangeEvent is a BehaviourRelay<String>
viewModel.textChangeEvent.asDriver().drive(cell.segmentedControl.rx.title(forSegmentAt: 0)).disposed(by: disposeBag)

```
The idea was just to provide a reactive way to change the text according to model changes. :))

**Comment by kzaher** [comment]
But wouldn’t a mote appropriate form be titleForSegment(at:).

**Comment by LucianoPAlmeida** [comment]
Ahh I see, sorry I miss understand the question before :)) 
I just follow the same naming pattern of the existing`enabled(forSegmentAt segmentAt: Int)`. 
But I agree that  `segmentedControl.titleForSegment(at: 0)` and sure can change it  :)

**Comment by kzaher** [comment]
Hi @LucianoPAlmeida ,

I think we've maybe made an error with `enabled(forSegmentAt segmentAt: Int)` :(.

**Comment by LucianoPAlmeida** [comment]
Hey @kzaher  
Thank you for the feedback :)) 
What do you think about this changes?

**Pull request merged**
