### PR TITLE
Use guard for simplification.

### PR DESCRIPTION
**Pull request by yoshinorisano**
When I was looking into the RxExample code, I thought it could be improved by using `guard` statements introduced in Swift 2.
Though it is not essential change for RxExample, if it is good for you, please consider merge it.
Thanks :)

### CODE REVIEW

**Comment by orta** [comment]
:dancers:

**Comment by kzaher** [comment]
This improves readability. Agreed :+1:

**Comment by kzaher** [comment]
Could you please point this to `develop` so I can merge it.

**Comment by kzaher** [comment]
This is a dupe :)

**Pull request closed without merging**
