### PR TITLE
Compile Swift 4.0 xcode9b3

### PR DESCRIPTION
**Pull request by carlosypunto**
Updated all to 4 and xc9b3
[WIP] Don't pass all tests

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @carlosypunto ,

Could you please make sure changes from `make all swift 4 xc9b3 for check` commit are only made once on `Rx` level and individual targets:
RxSwift-iOS
RxSwift-OSX
RxSwift-tvOS
...

just inherit the settings.

We don't want to have separate settings per target. 

The same is valid for RxExample project.

**Comment by kzaher** [comment]
... and Preprocessor/Preprocessor.xcodeproj/project.pbxproj

**Comment by kzaher** [comment]
I'm not sure why all of the Rx.xcodeproj/xcshareddata/xcschemes/*.xcscheme have language="". Do we need that?

**Comment by carlosypunto** [comment]
Hi @kzaher,

Yeah, `make all swift 4 xc9b3 for check` method was:
    - to pass migrator checking all its changes (some kill code)
    - Change __swift to 4__ and __disabled swift 3 objc inference__ in all targets of three projects
 includes in rx, preprocesor, example and scripts.
    - commit

About `language=""` i'm not sure but into xcode:
image

**Comment by kzaher** [comment]
Hi @carlosypunto ,

I don't think I've managed to explain what I meant there :)

I've made those changes and then cherry-picked your commits.

**Pull request closed without merging**
