### PR TITLE
Simplify by using forEach

### PR DESCRIPTION
**Pull request by ShenghaiWang**
Simplify code by using forEach

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @ShenghaiWang ,

The logic duplication there is due to performance reasons since bag is a commonly used data type. :)

**Comment by ShenghaiWang** [comment]
Thanks for your reply and having created such a beautiful framework.

Yes, I noticed that @inline(__always) annotation. In order to avoid this duplication, could we somehow make that forEach method as an inline method? Or add a fileprivate method in Bag+Rx.swift file to hold the enumeration logic, which then will be used by these two global methods?

To me, the duplication here is just not in line with the overall beauty of the framework :)

**Comment by kzaher** [comment]
@ShenghaiWang I agree that it's extremely ugly.

Unfortunately, there are various tradeoffs we've decided to make. This is just one of them.

We could try to do many different things to remedy this issue, but at the end of the day even though the solution could maybe work on a single compiler version (probably latest), optimizations could break without warning in any subsequent swift compiler version.

This is an ugly solution, but it's unit tested and at the end of day it's the least risky one IMHO.

I'm not worried that people would see this code and conclude that I couldn't see that this is duplicated logic and that there exists an obvious abstraction, even though this is probably constantly happening and people assume I'm clueless based on reading this code alone 😆😆😆.

**Comment by ShenghaiWang** [comment]
Understood. You needn’t worry that at all. Thanks again for this beautiful framework.

**Pull request closed without merging**
