### PR TITLE
Add Optional overloads for `from` operator

### PR DESCRIPTION
**Pull request by tarunon**
Discussed on #866 
- [x] Add Optional overloads for `from` operator.
- [x] Passed all tests.

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @tarunon ,

I think it's mostly ok, but there are a few changes that we would need to make.

I think there should be two versions (you can check out `just` operator implementation for more details).

```
public static func from(_ optional: E?) -> Observable<E>
public static func from(_ optional: E?, scheduler: ImmediateSchedulerType)
```

There are two reasons:
* optimizations, first overload without explicit scheduler will probably be most often used and will be significantly faster
* It will be more flexible when used as closure

```
func sum(first: Int, second: Int = 2) -> Int {
    return first + second
}

func sum2(first: Int) -> Int {
    return first + 2
}

func sum2(first: Int, second: Int) -> Int {
    return first + second
}

func doIt(action: (Int) -> Int) {
    
}

doIt(action: sum2) // works
//doIt(action: sum) // doesn't work
```

This was more important for `just` operator, but this one also seems close.

**Comment by tarunon** [comment]
OK, I understand that. I'll add overloads without `Scheduler` version.

By the way, Observable.from(Array) uses default argument that `CurrentThreadScheduler`.
Should we change Observable.from(Array) also? If it is correct, I'll fix that new PR. ☺️

**Comment by tarunon** [comment]
`Observable.from(Array)` has some of elements, maybe we'd use `CurrentThreadScheduler`. 🤔

**Comment by kzaher** [comment]
Hi @tarunon ,

Yeah, if it has multiple elements then some scheduler has to be used so emitting of elements can be cancelled any time, and `CurrentThreadScheduler` is a safe default that doesn't make any assumptions about the environment.

**Pull request merged**
