### PR TITLE
Check that aSelector is not nil before passing it on...

### PR DESCRIPTION
**Pull request by danielt1263**
Both `voidDelegateMethodsContain(_ :)` and `hasObservers(selector:)` require that `aSelector` is not nil. The `responds(to:)` method assumes it isn't nil but doesn't check. Some older objective-c libraries (eg, FSCalendar) check to see if the delegate responds to a `nil` selector.

This change adds code to return false if the selector is nil.

### CODE REVIEW

**Comment by danielt1263** [comment]
For more information, check out this StackOverflow question: https://stackoverflow.com/questions/68872523/error-occurred-when-i-using-rxswifts-delegateproxy-with-fscalendar/68873186#68873186

**Comment by faimin** [comment]
`guard` maybe a better way

```swift
guard aSelector != nil else {
    return false
}

return super.responds(to: aSelector)
                || (self._forwardToDelegate?.responds(to: aSelector) ?? false)
                || (self.voidDelegateMethodsContain(aSelector) && self.hasObservers(selector: aSelector))
```

**Comment by freak4pc** [comment]
Hey @danielt1263, sorry for the delay in replying :) 
I agree with @faimin, can you switch to an early return with `guard` for that case? Reads much better in my opinion. 

Thanks!

**Comment by danielt1263** [comment]
Done.

**Review by freak4pc — APPROVED** [review]
Thanks you!

**Pull request merged**
