### PR TITLE
[Feature] - OfType Operator

### PR DESCRIPTION
**Pull request by glwithu06**
- Implement `ofType` operator using type casting operator (`as`) in Swift
- Add `ofType` extension methods on `ObservableType`
- Create `OfType`, `OfTypeSink`class

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @glwithu06 ,

did you need this functionality in some practical use case?

**Comment by glwithu06** [comment]
Hi @kzaher 

Every ViewModel (I called it Binder) has Observable<UIEvent> as input and Observable<Display> as output in my architecture.
So, I need to handle every event by its type.
It is illustrated as follows.
screen shot 2017-12-21 at 10 43 29 am

Of course, it can be implemented with filter and map.
But I think this is better than combining two operators and `ofType` has been already implemented in others (RxKotlin, RxJava, RxGroovy, RxNet)

**Comment by kzaher** [comment]
Hi @glwithu06 ,

Maybe a better place to put this functionality would be in RxSwiftExt. @fpillet Thoughts?

We try to minimize the number of operators inside this library.

**Comment by glwithu06** [comment]
Yeah, I agree with that.
But I think the operator that is introduced in the webpage(http://reactivex.io/documentation/operators.html) should be implemented here.

**Comment by kzaher** [comment]
Hi @glwithu06 ,

The union of all of the operators on http://reactivex.io/documentation/operators.html isn't in any way related with the number of operators that we plan to ship by default in this library.

**Pull request closed without merging**
