### PR TITLE
[Pitch] Creating type abstracting relay types common duplicated logic

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
On Signal+Subscriptions there were two methods with the same implementation for two different types of Relays (`Publish` and `Behavior`). So maybe it's worth creating a protocol level of abstraction over relay and remove this duplication using the generic type. It's a very little duplication and maybe doesn't worth the abstraction. 
@kzaher and @freak4pc let me know your thoughts on this one :)

### CODE REVIEW

**Comment by freak4pc** [comment]
I think there was already a discussion about unifying binding related operations that was rejected 
https://github.com/ReactiveX/RxSwift/pull/155

In any way even if we want to unify Relays as a single thing it needs to happen for all types, not just Signal. I’d suggest leaving this open to see if Krunoslav could take a peek.

**Comment by LucianoPAlmeida** [comment]
Now I see the point, thank you :)) 
I think this one is specific to Relay types, more conceptual abstraction around `accept()`. And different form 1551 it doesn't affect ObserverType and by doing that being an abstraction only affecting RxCocoa scope and Relay types `Publish` and `Behavior`. 
This is more a pitch to bring the discussion and feel  free to close if this doesn't fit :))

**Comment by LucianoPAlmeida** [comment]
Just updating the pitch :))
Also, this is something that can be done with a class `Relay<Element>` with an "abstract" method `accept` where `PublishRelay` and `BehaviorRelay` inherits from it. 
But now I'm thinking about it better and maybe this whole pitch seems like an over-abstraction, not sure 😆

**Comment by kzaher** [comment]
Hi @LucianoPAlmeida ,

The purpose of the particular overloads was to only allow particular types of binds.

> But now I'm thinking about it better and maybe this whole pitch seems like an over-abstraction, not sure 😆

Yeah, this seems to me like an over-abstraction.

**Comment by LucianoPAlmeida** [comment]
I see the point 👍 
Closing this then, thank's for the comments @freak4pc @kzaher :))

**Pull request closed without merging**
