### PR TITLE
Implement UIWebView+Rx

### PR DESCRIPTION
**Pull request by AndrewSB**
continuation of #855

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @AndrewSB ,

It looks like unit tests are failing for some reason. Do they pass when you run `./scripts/all-tests.sh` locally?

**Comment by AndrewSB** [comment]
@kzaher I took a look at the tests locally, and was able to fix the issues travis *was* having 👍 

But it turns out that the three delegate methods I'm testing (`didStartLoad`, `didFinishLoad`, and `didFailLoad `) are async, so the `XCTAssert`'s are failing because the tests are being run synchronously. 
Do you have any experience with this kind of situation?

**Comment by kzaher** [comment]
Hi @AndrewSB ,

you won't be able to load anything from the internet since that in unreliable to have in unit tests.

Please create a small html file inside test target. You can use blocking operators to make sure that method will be called and unit test waits until it receives some event.

**Comment by AndrewSB** [comment]
@kzaher I've updated the tests to not hit the network, but now travis seems to be failing because of danger: `The command "if [ "${DANGER}" -eq 1 ]; then bundle exec danger --verbose; else xcodebuild -version; xcodebuild -showsdks; ./scripts/all-tests.sh "${TEST}"; fi" exited with 65.`

Not sure what's up

**Comment by AndrewSB** [comment]
@kzaher anything else holding this back from being merged?

**Comment by sergdort** [comment]
@AndrewSB  CI fail 😉

**Comment by AndrewSB** [comment]
Ahh, I looked closer at the CI message, I thought it was an issue with the CI, not the code I wrote.

**Comment by AndrewSB** [comment]
Not sure why this is failing,
It seems to be something with Travis?

```
Done. Your build exited with 1.
/Users/travis/build.sh: line 109: shell_session_update: command not found
```

**Comment by kzaher** [comment]
Hi @AndrewSB ,

yeah, travis is behaving weird. I'm assuming it's because of xcodebuild and simulator startup time.

There are two things we would need to change to merge this.

I think the library code is ok, but unit tests look little weird right now, so hoping these guidelines would help you :)
I think it's simplest to just have something like https://github.com/ReactiveX/RxSwift/blob/master/Tests/RxCocoaTests/UITableView%2BRxTests.swift#L58-L62
We only need to make sure that when delegate method fires event is being dispatched through observable sequence.
The other test we need to add is delegate proxy subclassing test. https://github.com/ReactiveX/RxSwift/blob/master/Tests/RxCocoaTests/DelegateProxyTest%2BUIKit.swift#L108-L110

It would be also great if you could squash all of those commits into a couple of them (ideally one, but a couple is also ok).

**Comment by AndrewSB** [comment]
I'm having some trouble understanding the delegate proxy subclassing test. I've created the `UIWebViewSubclass` that conforms to `TestDelegateControl`, but right now I'm crashing on `checkSelectorIsObservable`...

Why would my subclass respond to `testEventHappened:`? I don't implement that selector for my delegate proxy - should I?

**Comment by AndrewSB** [comment]
Hmm, I was able to fix the test failure by adding this line of code `extension RxWebViewDelegateProxy: TestDelegateProtocol {}`. What is the purpose of the test? It seems contrived to unknowing little me 👶

**Comment by AndrewSB** [comment]
Can you comment more directly on what you dislike of the style? Is it that I've created an `htmlString`, and I'm using that to pass the tests? If so, I can do this instead https://github.com/ReactiveX/RxSwift/pull/857/commits/378dd5ba6a46df189a9b2f042ee285175feb028d.
Or is it the use of `toBlocking().first()`? If that's the case, then I'm not sure how to rewrite the tests. If I write the test as a subscription that mutates a variable, and then send the webView a request to load, then my test fails (as the webView delegate methods are async). I need something that blocks for the tiniest amount of time

Once this is ready to go, I'll happily squash this into 2-3 commits 😄

**Comment by ikesyo** [comment]
> Or is it the use of `toBlocking().first()?` If that's the case, then I'm not sure how to rewrite the tests. If I write the test as a subscription that mutates a variable, and then send the webView a request to load, then my test fails (as the webView delegate methods are async). I need something that blocks for the tiniest amount of time

You can use `XCTestExpectation`.

**Comment by AndrewSB** [comment]
Can I ask another question? Why do some delegate proxies require delegate methods overridden, while others don't?

For instance, the web view delegate proxy doesn't require `webViewDidFinishLoading(_:)` implemented, but `RxScrollViewDelegateProxy` implements `scrollViewDidScroll`. Why is that?

**Comment by AndrewSB** [comment]
@ikesyo I've used the super cool async `XCTestExpectation`
@kzaher I've rebased my commits

Let me know if there's anything else I should do!

**Comment by AndrewSB** [comment]
@ikesyo I realized I could write the tests by just calling the delegate methods, as @kzaher said in https://github.com/ReactiveX/RxSwift/pull/985#issuecomment-259265107, so I removed `XCTestExpectation`, but thank you for showing it to me!

**Comment by AndrewSB** [comment]
🙏

**Pull request merged**
