### PR TITLE
make control property init method public

### PR DESCRIPTION
**Pull request by frogcjn**
make control property init method public

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @frogcjn ,

I think a lot of people want this public, I guess it makes sense for it to be public.

I would ask you to just do these things so I can merge this:
* can you please point PR to `develop` branch
* If you could do the same for `ControlProperty` that would be great
* could you just add two corresponding unit tests for those constructors. I would like to have all public interface covered with at least one test, so I know if there was some breakage of public interface

:)

**Comment by frogcjn** [comment]
I'll point to develop branch.
While, I'm not familiar with unit test and I don't know too much about the underlaying event system of RxSwift, so it is hard for me ti write the unit tests.

**Comment by kzaher** [comment]
Oh, I'll write them after merging, no problem :)

**Comment by kzaher** [comment]
Hey, 

This was sitting here for a while. I guess it didn't get pointed to `develop` branch :)

Meanwhile I did made those changes, commented then, noted warnings and added unit tests in 827ee57fff6a80f79a9ecf7e90dcc7459caeaae0

Closing this one.

**Pull request closed without merging**
