### PR TITLE
@frozen CompletableEvent

### PR DESCRIPTION
**Pull request by marcelofabri**
Like #2271, but for `CompletableEvent`

### CODE REVIEW

**Review by freak4pc — APPROVED** [review]

**Comment by freak4pc** [comment]
Thanks for both PRs @marcelofabri

**Comment by reidmain** [comment]
Hey @freak4pc, what are your thoughts on cutting a minor release to get this change and https://github.com/ReactiveX/RxSwift/pull/2271 out there? Being able to remove `@unknown default` would really help clean up some of the code I've be dealing with lately.

**Comment by freak4pc** [comment]
Hey @reidmain, I plan to release 6.1 in the following week anyways so It'll include this as well.

**Comment by reidmain** [comment]
> Hey @reidmain, I plan to release 6.1 in the following week anyways so It'll include this as well.

Excellent. Thank you very much for your prompt response.

**Pull request merged**
