### PR TITLE
[WIP] Create a Subject that can't error

### PR DESCRIPTION
**Pull request by AndrewSB**
@kzaher started working on this from #922 

Facing two things currently:
1. Not a huge fan of the name `ErrorlessSubject`, would love suggestions to change it to anything else. You mentioned `Event`, but I had an issue implementing that (https://github.com/ReactiveX/RxSwift/issues/922#issuecomment-252131282)
2. I'm not sure how best to implement this. I'll take some time and look at the implementation of `Driver`, see if that takes me anywhere.
3. Should this be in the `RxSwift`, or `RxCocoa` target?

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @AndrewSB ,

I would need to think about where should be put this, and how should it be called.

The reason why we've added `Variable` to RxSwift is because the chances of somebody new to the library finding `BehaviorSubject` was so slim.

I wouldn't want to deviate too much from other implementations.

**Comment by kzaher** [comment]
Hi @AndrewSB ,

I've been thinking about this, and right now we have a nice pipeline for state propagation.

BehaviorSubject or Variable or ControlProperty (write part) -> Driver (read only view with certain guarantees)

And it really looks like we don't have such nice pipeline for event modeling. 

I think that we could add to RxCocoa `Publisher` that wraps `PublishSubject` and can't error out in the same way `Variable` wraps `BehaviorSubject`.

Something like
```
class Publisher<E> {
     func publish(event: E)

     func asObservable() -> Observable<E>
}
```

Maybe we can create a specialization for `SharedSequence` with `Publish` strategy and name it something like `EventBus`/`Event`/`EventSource`. Still unsure about the name. Open to suggestions.

Then one could have:
```swift
let publisher = Publisher<()>()
let events = publisher.asEventSource().map { }.filter { }.withLatestFrom(stateDriver) .....

publisher.publish()
```

I still need to make loosen constraints on SharedSequence so it would be possible to combine `Driver` and `EventSource`ish sequence.

Maybe it would make sense for RxSwift 4.0 to move `Variable`, `Driver`, `Event`, `ControlProperty`, `ControlEvent` from RxCocoa to separate RxUnits project and keep RxCocoa pure and focused on just extensions, but let's not think about this for now. I think it's fine for RxCocoa to contain them for now.

In the future if Swift 4.0 adds generic error parametrization and we add generic error type to `PublishSubject` it would still make sense to have something like `Publisher` for easier interaction with imperative parts of the app.

**Comment by AndrewSB** [comment]
@kzaher that sounds absolutely lovely. `Publisher` and `Variable` sound great to me.

I'll wait for you to
> loosen constraints on SharedSequence so it would be possible to combine Driver and EventSourceish sequence.

and then continue with this PR. Give me a holler when you're done?

**Comment by kzaher** [comment]
Hi @AndrewSB ,

I think we can add `Publisher` that is equivalent to `Variable` and `EventBus` that is equivalent to `Driver`.

While Googling, I've accidentally also found some other project that is using the same terminology :)

https://github.com/greenrobot/EventBus

**Comment by kzaher** [comment]
I was maybe a bit too quick on naming, but don't have any better ideas.

**Comment by DenHeadless** [comment]
Would really want this subject to exist. I've been searching for this kind of functionality recently, trying to replicate what Kickstarter guys did with their ViewModel event transformation like so: 
[https://github.com/kickstarter/ios-oss/blob/master/Library/ViewModels/CommentsViewModel.swift#L177-L215](url)

For events that have default value it's nice to use `Variable`. But for events that have not, for example tap a login button i'm forced to use PublishSubject, even though i know for sure that it will never error - i'm only sending next events, and transform them into outputs.

`Publisher` sounds nice, i would like to help make this, if i can. Was there any progress on this?

**Comment by kzaher** [comment]
I think this is superseded by #1116

**Comment by AndrewSB** [comment]
Yes, it is 😊

**Pull request closed without merging**
