### PR TITLE
Fix RxBlocking in Swift 3

### PR DESCRIPTION
**Pull request by tomburns**
Remove force cast in favor of rawValue to fix crash at runtime

### CODE REVIEW

**Comment by tomburns** [comment]
Noticing now that several (but not all) tests that use RxBlocking appear to be deadlocking... 😕

**Comment by tomburns** [comment]
Found that a source of "deadlock" was actually just incorrect conversion of the interval in `ConcurrentDispatchQueueScheduler.schedulePeriodic` and fixed it

**Comment by tomburns** [comment]
Taking a look at why `ObservableConcurrentSchedulerConcurrencyTest2.testObserveOn_EnsureTestsAreExecutedWithRealConcurrentScheduler()` is still hanging, though it passes when run in isolation; any insight would be welcome as this one might have me stumped 🤒

**Comment by tomburns** [comment]
Regardless of the remaining issues, I'm pretty sure these fixes are mergeable as-is; we can continue tackling the rest of the issues separately. Let me know if there's anything else I can do to wrap up this PR.

**Comment by kzaher** [comment]
Hey, these changes look ok to me. Yeah, I think there are some issues left that we need to solve after this one.

I'll try to release 2.6 today, so I can concentrate on 3.0 after that.

**Pull request merged**
