### PR TITLE
reactive wrapper for UIPopoverPresentationController

### PR DESCRIPTION
**Pull request by vldalx**
The pull request adds a reactive wrapper for UIPopoverPresentationController.
Extensions:
- `prepareForPresentation`
- `willReposition`
- `didDismiss`

### CODE REVIEW

**Comment by freak4pc** [comment]
Thanks for the contribution @vldalx. I think there is an attempt to keep RxSwift core as light as possible and reduce the amount of code we add here. 

I feel like a better place for this extension will be at RxSwiftCommunity/RxSwiftExt. What do you think?

**Comment by vldalx** [comment]
According to [Human Interface Guidelines](https://developer.apple.com/ios/human-interface-guidelines/views/popovers/), generally, popovers should be reserved for use in iPad apps. So, it means a small percentage of all the iOS apps use popovers. From this perspective, the best place for the extension is `RxSwiftExt`.

On the other hand, `UIPopoverPresentationController` is a part of `UIKit` and `RxCocoa` is a framework that helps make Cocoa APIs easier to use with reactive techniques.

**Comment by freak4pc** [comment]
@vldalx RxCocoa Core doesn't include _any_ Cocoa/UIKit APIs. 
Only extremely popular ones, and usually code isn't added on this repo in general unless its an extremely requested feature.

I'd suggest perhaps proposing this as an issue in RxSwiftExt, but in general I think this might be too much of a "niche" to make an extension for in a public repo, that's just my opinion though :)

**Comment by freak4pc** [comment]
@vldalx Are you OK with closing and moving this to RxSwiftExt possibly?

**Comment by vldalx** [comment]
@freak4pc I completely forgot about this RP. I'll close and move it in two weeks.

**Comment by freak4pc** [comment]
Cool. Closing this for now, the branch still lives so you may transfer in your free time. 

Thanks!

**Comment by vldalx** [comment]
@freak4pc 
I'm moving this PR to `RxSwiftExt`. However, there is a problem with it.
In order to move tests it's necessary to have [RxTest](https://github.com/ReactiveX/RxSwift/blob/master/Tests/RxTest.swift) class in `RxSwiftExt`. Should I copy that class?

**Comment by freak4pc** [comment]
RxSwiftExt already uses RxTest for tests: https://github.com/RxSwiftCommunity/RxSwiftExt/blob/master/Tests/RxSwift/MapManyTests.swift#L11

**Comment by vldalx** [comment]
My question wasn't about `RxTest` framework
https://github.com/ReactiveX/RxSwift/blob/e27cded029c8c0df61d4f4778705921015f5741b/Tests/RxTest.swift#L11
It was about `RxTest` class
https://github.com/ReactiveX/RxSwift/blob/e27cded029c8c0df61d4f4778705921015f5741b/Tests/RxTest.swift#L47-L48
It's the base class for tests instead of `XCTestCase`.

**Comment by freak4pc** [comment]
@vldalx That's fine, you'll just have to refactor your test to not use `RxTest` as its a helper class of `RxSwift` itself. I don't see why you'd forcefully need it just to write a test for this.

**Pull request closed without merging**
