### PR TITLE
Add rx wrapper for UITableViewDelegate tableVIew:accessoryButtonTappedForRowWithIndexPath: method

### PR DESCRIPTION
**Pull request by mwoollard**
Had a need for this is something I was working on - would seem to make sense to include this delegate method? Included its use in the simple table view example.

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @mwoollard, I think we could include this if you could add unit tests for this extension.

**Comment by mwoollard** [comment]
OK will do

**Comment by mwoollard** [comment]
Have added unit test following pattern used for the other table view delegate / data source rx extensions.

**Comment by kzaher** [comment]
Hi @mwoollard ,

If you could solve merge conflicts, I would be happy to merge this.

**Comment by mwoollard** [comment]
Will do - may take a few days to get to it - lot going on right now !

**Comment by mwoollard** [comment]
Should be all good now

**Pull request merged**
