### PR TITLE
Modified completed condition of zip

### PR DESCRIPTION
**Pull request by FuYouFang**
If there Three Observables like this:

|  | E1 | E2 | E3 | E4 | E5 | E6 |
| -- | -- | -- | -- | -- | -- | -- |
| O1 | 🍎| 🍎| 🍎| 🍎| 🍎| completed |
| O2 | 🍎| 🍎| 🍎| completed | | |
| O3 | 🍎| completed | | | | |

Should it end at E2 or should it end at E4 ?

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @FuYouFang ,

I believe it should actually end at E6. The current behavior is confusing and we need to change this for sure. 

We are tracking this under https://github.com/ReactiveX/RxSwift/issues/1666

This is intended for RxSwift 5.0. If you like to do the changes, you are welcome.

**Comment by MortyMerr** [comment]
Hey @kzaher what's the final solution on that? Conclusion in issue and in this PR seems to be different :(

**Comment by kzaher** [comment]
We've made the changes to end at `E6` and released them in 5.0.

**Comment by c0diq** [comment]
This changes has impacted our tests. It appears that a TestScheduler.start() method will now never return in some cases (deadlock) when that scheduler is used in an Observable that never completes. I will file a ticket separately.

**Pull request closed without merging**
