### PR TITLE
Update Examples.md

### PR DESCRIPTION
**Pull request by darrensapalo**
Typo; fixed `RxSwit` into `RxSwift`

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @darrensapalo ,

if you could redirect this PR to `develop` branch, I would be happy to merge it :)

**Comment by darrensapalo** [comment]
Will do! Not sure how to do that but i'll google it. (New to open source contribution)

**Comment by thanegill** [comment]
You'll need to create a new PR that points to the `develop` branch

**Comment by kzaher** [comment]
I've just merged correct one to `develop`. Can close this one.

**Pull request closed without merging**
