### PR TITLE
use os_unfair_lock implement spin lock.

### PR DESCRIPTION
**Pull request by longjianjiang**
Try running AllTests-* target. All success.

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey, seems like CI is failing. But regardless, could you share what's the advantage of this ? Also please attach a benchmark to this PR. Thanks!

**Comment by longjianjiang** [comment]
```
func benchmark() {
        let count = 10000

        do {
            var lock = os_unfair_lock_s()
            let begin = CACurrentMediaTime()
            for _ in 0..<count {
                os_unfair_lock_lock(&lock)
                os_unfair_lock_unlock(&lock)
            }
            let end = CACurrentMediaTime()
            print("os_unfair_lock: %8.2f ms\n", (end - begin) * 1000)
        }

        do {
            var lock = pthread_mutex_t()
            pthread_mutex_init(&lock, nil)
            let begin = CACurrentMediaTime()
            for _ in 0..<count {
                pthread_mutex_lock(&lock)
                pthread_mutex_unlock(&lock)
            }
            let end = CACurrentMediaTime()
            pthread_mutex_destroy(&lock)
            print("pthread_mutex_t: %8.2f ms\n", (end - begin) * 1000)
        }

        do {
            let lock = NSRecursiveLock()
            let begin = CACurrentMediaTime()
            for _ in 0..<count {
                lock.lock()
                lock.unlock()
            }
            let end = CACurrentMediaTime()
            print("NSRecursiveLock: %8.2f ms\n", (end - begin) * 1000)
        }
    }
```

```
 func benchmarkMultipleThread() {
        let queue = DispatchQueue(label: "async", attributes: .concurrent)
        let count = 10000

        queue.async {
            let begin = CACurrentMediaTime()
            do {
                var lock = os_unfair_lock_s()
                for _ in 0..<count {
                    os_unfair_lock_lock(&lock)
                    os_unfair_lock_unlock(&lock)
                }
            }
            let end = CACurrentMediaTime()
            print("os_unfair_lock: %8.2f ms\n", (end - begin) * 1000)
        }

        queue.async {
            let begin = CACurrentMediaTime()
            do {
                var lock = pthread_mutex_t()
                pthread_mutex_init(&lock, nil)

                for _ in 0..<count {
                    pthread_mutex_lock(&lock)
                    pthread_mutex_unlock(&lock)
                }
                pthread_mutex_destroy(&lock)
            }
            let end = CACurrentMediaTime()
            print("pthread_mutex_t: %8.2f ms\n", (end - begin) * 1000)
        }

        queue.async {
            let begin = CACurrentMediaTime()
            do {
                let lock = NSRecursiveLock()
                for _ in 0..<count {
                    lock.lock()
                    lock.unlock()
                }
            }
            let end = CACurrentMediaTime()
            print("NSRecursiveLock: %8.2f ms\n", (end - begin) * 1000)
        }
    }
```

running on Xcode11.0 beta3, iPhone8 Simulator, output:

```
single thread: 
os_unfair_lock: %8.2f ms
 0.24522095918655396
pthread_mutex_t: %8.2f ms
 0.2889679744839668
NSRecursiveLock: %8.2f ms
 0.7482669316232204

multiple thread: 
os_unfair_lock: %8.2f ms
 0.2481420524418354
pthread_mutex_t: %8.2f ms
 0.3236010670661926
NSRecursiveLock: %8.2f ms
 0.7782229222357273

```

**Comment by freak4pc** [comment]
I meant that there’s a benchmark target for RxSwift... could you run that please before and after your changes ? :)

**Comment by longjianjiang** [comment]
running on Xcode11.0 beta3, My Mac.

before change, benchmark test output:

```
Test Suite 'Benchmarks' passed at 2019-07-26 09:44:49.443.
	 Executed 13 tests, with 0 failures (0 unexpected) in 365.774 (365.783) seconds
Test Suite 'Benchmarks.xctest' passed at 2019-07-26 09:44:49.444.
	 Executed 13 tests, with 0 failures (0 unexpected) in 365.774 (365.785) seconds
Test Suite 'All tests' passed at 2019-07-26 09:44:49.444.
	 Executed 13 tests, with 0 failures (0 unexpected) in 365.774 (365.787) seconds
```

after change,  benchmark test output:

```
Test Suite 'Benchmarks' passed at 2019-07-26 10:02:43.059.
	 Executed 13 tests, with 0 failures (0 unexpected) in 360.082 (360.091) seconds
Test Suite 'Benchmarks.xctest' passed at 2019-07-26 10:02:43.060.
	 Executed 13 tests, with 0 failures (0 unexpected) in 360.082 (360.094) seconds
Test Suite 'All tests' passed at 2019-07-26 10:02:43.061.
	 Executed 13 tests, with 0 failures (0 unexpected) in 360.082 (360.095) seconds
```

**Comment by longjianjiang** [comment]
I tested in an asynchronous environment,  `os_unfair_lock` is much faster than `NSRecursiveLock`.

And we use locks to prevent multiple thread competition, so using os_unfair_lock or pthread_mutex_t will get better performance when spin lock conditions are needed.

**Comment by freak4pc** [comment]
@longjianjiang Tests are still failing, could you resolve this? Thanks.

**Comment by kzaher** [comment]
It seems to me that we have a 1% change according to the reported results. I haven't tried running anything myself because I've been trying these kinds of experiments a while ago and decided that the risk of introducing bugs is far greater than the potential benefit.

`NSRecursiveLock` already uses `pthread_mutex_t` internally. 

The biggest overhead in RxSwift is Swift itself. Locking code only represents a tiny fraction of the cost.

**Comment by longjianjiang** [comment]
```
/home/travis/build/ReactiveX/RxSwift/Sources/RxSwift/Lock.swift:20:30: error: use of unresolved identifier 'os_unfair_lock_s'
    private var unfairLock = os_unfair_lock_s()
                             ^~~~~~~~~~~~~~~~
/home/travis/build/ReactiveX/RxSwift/Sources/RxSwift/Lock.swift:23:9: error: use of unresolved identifier 'os_unfair_lock_lock'
        os_unfair_lock_lock(&unfairLock)
        ^~~~~~~~~~~~~~~~~~~
/home/travis/build/ReactiveX/RxSwift/Sources/RxSwift/Lock.swift:27:9: error: use of unresolved identifier 'os_unfair_lock_unlock'
        os_unfair_lock_unlock(&unfairLock)
```

CI build failed in linux,  `os_unfair_lock` not available in linux? @freak4pc

**Comment by freak4pc** [comment]
Could be ... so we can't use /:

Also given Kruno's note - I'm not sure it would necessarily make sense to use for a relatively minor performance impact.

**Comment by longjianjiang** [comment]
Already seen Kruno's note , i'm not sure should this be added /:

**Comment by freak4pc** [comment]
Hey @longjianjiang - I'm closing this for now. The risk is too high and the performance impact is minor. Feel free to comment here if you still want to pursue this in a different way. Thank you for your work!

**Pull request closed without merging**
