### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by nighthawk**
Tiny fix, discovered while browsing examples.

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @nighthawk ,

Thnx for finding this problem. If you could fix build failure and target this PR to `develop` branch, I would be happy to merge this
```
❌  /Users/travis/build/ReactiveX/RxSwift/RxExample/RxExample/Examples/GeolocationExample/GeolocationViewController.swift:51:9: value of type 'GeolocationService' has no member 'autorized'
        geolocationService.autorized
        ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~
```

**Comment by kzaher** [comment]
Anybody wants to help fix this?

**Comment by carlosypunto** [comment]
If not is a problem, I get to work :slightly_smiling_face:

**Comment by carlosypunto** [comment]
Fixed in PR https://github.com/ReactiveX/RxSwift/pull/700

**Comment by nighthawk** [comment]
Thank you!

**Pull request closed without merging**
