### PR TITLE
Remove unneeded return statements

### PR DESCRIPTION
**Pull request by sticksen**
This PR removes all unneeded return statements as described in https://github.com/apple/swift-evolution/blob/master/proposals/0255-omit-return.md
This code change can be done when using Swift 5.1, so I´m targetting this branch with my PR.

### CODE REVIEW

**Comment by freak4pc** [comment]
Thanks for the PR @sticksen ! 
While this is a nice ability and we _can_ omit returns, we still haven't decided if this is the style we want to follow in this repo. 

@kzaher wdyt? I know you like explicitness in these kind of things, so let me know your thoughts.

**Comment by kzaher** [comment]
@freak4pc I'm fine with these `return` removals. Seems like having `return` doesn't improve readability much.

On the other hand, I don't think that changes to `scripts/validate-podspec.sh` are good. These changes are there to allow CI to process major version bumps.

**Comment by freak4pc** [comment]
It was one of my attempts, I'm not sure why he has that commit in his PR. Can you remove it @sticksen ?

**Comment by sticksen** [comment]
No problem, will remove it!

**Comment by sticksen** [comment]
It´s ready for reviewing again, @kzaher, @freak4pc

**Comment by freak4pc** [comment]
I believe I addressed all of these in https://github.com/ReactiveX/RxSwift/commit/8dd25b4637cb64d44b0d644f37427803c24f1343

**Pull request closed without merging**
