### PR TITLE
Prefer private over fileprivate

### PR DESCRIPTION
**Pull request by MortyMerr**
Swift 3 is gone and we can use private properties in extensions. Also, there are few other cases when `fileprivate` can be replaced with `private`. 
Pros:
- compiler will provide optimizations
- contributor will be less confused with `fileprivate` usage

### CODE REVIEW

**Comment by MortyMerr** [comment]
Sorry, change target branch

**Comment by MortyMerr** [comment]
CI is green now :)

**Comment by kzaher** [comment]
I think it might be worthwhile to investigate how can we make sure we don't break ABI with changes. Unsure how to do that.

**Comment by freak4pc** [comment]
I'm not sure it necessarily matters if we release new versions - binary stability is nice, but people are still locked in to specific versions of the library, that's what versions are for. WDYY?

**Comment by kzaher** [comment]
@freak4pc 

> I'm not sure it necessarily matters if we release new versions - binary stability is nice, but people are still locked in to specific versions of the library, that's what versions are for. WDYT?

It would be nice to maintain backwards stable ABI because it seems some people expect that and are depending their closed source libraries on us.

I would say that would we want to maintain backwards stable ABI depends on the amount of effort we need to put into it. If we can automate this in some easy way, then I would say yes, otherwise no.

**Comment by freak4pc** [comment]
@kzaher A bit confused on why, since closed source libraries are also versioned (usually) and possibly locked to a specific API version. ABI is useful in case of Swift where things come bundled on devices, etc, but is it really making a huge difference here? 

About automation I guess the .swiftmodule option suggested by @LucianoPAlmeida (I think) could do it, but not 100% sure it's worth it in any way.

**Comment by kzaher** [comment]
Let's continue this here #2026.

**Pull request merged**
