### PR TITLE
Add driver subscription to PublishRelay

### PR DESCRIPTION
**Pull request by yuzushioh**
I added driver subscription to PublishRelay

### CODE REVIEW

**Comment by yuzushioh** [comment]
oh there are already `emit` methods for `PublishRelay` 😅

**Comment by kzaher** [comment]
Hi,

`Driver` represents state `share(replay: 1)`, so it shouldn't make sense to `drive` something that has `share()` strategy, like `PublishRelay`.

**Comment by yuzushioh** [comment]
Hi @kzaher 
I see your point. how about `BehaviorRelay` having `drive` subscriptions? I might have misunderstood but I thought `BehaviorRelay` doesn't represent `share(replay: 1)`. I don't understand how it makes sense here.

**Comment by kzaher** [comment]
Hi @yuzushioh ,

I would rather not add some public interface if we don't have compelling reasons do so. I doubt users will need to do `behaviorSubject.asDriver().drive` often, or ever :)

**Pull request closed without merging**
