### PR TITLE
Run playgrounds in pre-release-tests.sh

### PR DESCRIPTION
**Pull request by yury**
A little bit ugly, but we can run playgrounds now.

### CODE REVIEW

**Comment by yury** [comment]
screen shot 2015-10-29 at 02 21 04

**Comment by yury** [comment]
screen shot 2015-10-29 at 14 11 40

screen shot 2015-10-29 at 14 14 33

**Comment by orta** [comment]
This is clever :+1:

**Comment by kzaher** [comment]
Awesome, thnx :)

**Pull request merged**
