### PR TITLE
Adds two rx properties to Cocoa controls.

### PR DESCRIPTION
**Pull request by mrahmiao**
1. Adds `rx_enabled` to `NSControl`
2. Adds `rx_state` to `NSButton`

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @mrahmiao ,

I was studying your PR, but I still need to do some investigation. I don't have much experience on OSX, so I'm not sure how is that `state` used, and how to subscribe to it's changes :)

I'll need to investigate on that one.

I don't have any other objections so far.

**Comment by kzaher** [comment]
Hi @mrahmiao ,

I've taken a close look at proposed changes. If you could just resolve merge conflicts and make build server happy, I would be happy to merge this. :)

**Comment by mrahmiao** [comment]
@kzaher I am not sure how to do so :[

**Comment by kzaher** [comment]
I believe that you would want to do rebase instead of merge. That would probably work.

**Comment by mrahmiao** [comment]
@kzaher It seems that everything messed up. I think I should close this PR and open a new one based on the develop branch. T.T

**Pull request closed without merging**
