### PR TITLE
Add AllSatisfy operator

### PR DESCRIPTION
**Pull request by MortyMerr**
No words about Combine. 
`allSatisfy` is a Swift.Sequence member. It might be useful for dealing with sequences.
https://developer.apple.com/documentation/swift/sequence/2996794-allsatisfy

If you find it useful, I will also add it for `SharedSequence`
https://github.com/ReactiveX/RxSwift/issues/2007

### CODE REVIEW

**Comment by MortyMerr** [comment]
@freak4pc what do you think?)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by freak4pc** [comment]
@MortyMerr Thanks for the work you've put into this. 

It's a nice idea in general - But I'm trying to think if there is a practical use-case to it. Yes, it exists in Combine and Swift Foundation, but I think the approach lately was to figure out "Does someone in the community actually find this useful for a real-life application?" 

What do you think? I can find many ideas for using this on a collection, but not as many real applications for a stream of values over time.

**Comment by freak4pc** [comment]
Hey @MortyMerr - I'm still contemplating about this one. I'm wondering if you found a practical use case to this. Thought about this some more but still find this very hard to reason about. 

There is a huge difference between allSatisfy for finite sequences / collections and something like a possibly infinite stream — not from the technical perspective, but from the usability perspective. I can't really think of a feature where this ability would help, but am happy to learn otherwise. 

Thank you!

**Comment by MortyMerr** [comment]
Feel free to close 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
