### PR TITLE
Add watchOS2 target

### PR DESCRIPTION
**Pull request by cfraz89**
We've recently successfully used RxSwift in a watchOS 2 app. We just had to do two things:
1. Add targets for watchOS
2. Turn 'embedded content contains swift code' to NO, otherwise the built app ends up with a second copy of the Swift runtimes. This should probably be disabled for the other targets too, however have left them as is for this PR.

Hopefully we can leave this target in the mainline RxSwift, and soon, tvOS :)

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @cfraz89 ,

I'll check it out little later, thnx for trying to help out.

Could you just please in the mean time target this PR to `develop` branch :)

**Comment by kzaher** [comment]
I've checked it out, 

generally looks ok, but I did see a problem that Unit tests for watch os can't compile :(, so not sure what to do about that.

It looks like @bontoJR  is also WAT.ch man. @bontoJR have you tried this on device and do you maybe know what to do with those watch tests?

**Comment by bontoJR** [comment]
Planned for tomorrow, self-assigned this issue :)

**Comment by kylef** [comment]
Remember to add the `watchOS` platform to the Podspec.

**Comment by kzaher** [comment]
I think we'll also need to add watchOS files, but kind of thought, oh well, if people test that fine, if not, oh well :)
```
  s.ios.deployment_target = '8.0'
  s.osx.deployment_target = '10.9'
  s.watchOS.deployment_target = #WAT? :)
  s.tvOS.deployment_target = #WAT? :)

  s.source_files          = 'RxCocoa/RxCocoa.h', 'RxCocoa/Common/**/*.{swift,h,m}'
  s.ios.source_files      = 'RxCocoa/iOS/**/*.swift'
  s.osx.source_files      = 'RxCocoa/OSX/**/*.swift'
  s.watchOS.source_files = 'RxCocoa/iOS/**/*.swift' # is this correct?
  s.tvOS.source_files = # WAT? :)
```

any help is welcome :)

I know that tv os is in another branch, but still :)

**Comment by bontoJR** [comment]
After few hours of work, here I am. 

I created a dedicated feature branch for this, I was able to compile and update the test script, unfortunately there's no XCTest, so no way to get tests running on WatchOS. 
https://github.com/Quick/Quick/issues/333
[rdar://21760513](https://openradar.appspot.com/21760513)

The code compiles, I was able to quickly import it into a basic project and in the simulator it works without any issue.

Now, I would prefer to delay the import of this into `develop` until I am sure there're no issues on the real device, I will try to test this on the next 2-3 days. 

About the Podspec, the update is [simple](http://blog.cocoapods.org/CocoaPods-0.38/) `s.watchos.deployment_target`.

FYI, this is the output of tests in WatchOS
```
RxSwiftTest-AppleWatch-watchOS_2.0 exists

test RxTests-watchOS - Release (RxSwiftTest-AppleWatch-watchOS_2.0)

2015-09-23 00:06:37.019 xcodebuild[56863:708501] [MT] IDETestOperationsObserverDebug: (39A95636-41E2-44F8-8DA3-52D7CACA15A9) Beginning test session with Xcode 7A218 on target <DVTiPhoneSimulator: 0x7f8dc4e36d20> {
		SimDevice: SimDevice : RxSwiftTest-AppleWatch-watchOS_2.0 (9E737018-78B0-420D-BD70-3830BC99401D) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm } runtime={ SimRuntime : 2.0 (13S343) - com.apple.CoreSimulator.SimRuntime.watchOS-2-0 }
} (2.0 (13S343))
▸ Building Rx/RxSwift-watchOS [Release]
▸ Compiling ReplaySubject.swift
▸ Compiling Observable+Extensions.swift
▸ Compiling Throttle.swift
▸ Compiling AsObservable.swift
▸ Compiling ObserverBase.swift
▸ Compiling ConnectableObservable.swift
▸ Compiling DistinctUntilChanged.swift
▸ Compiling Multicast.swift
▸ Compiling PublishSubject.swift
▸ Compiling AnonymousObservable.swift
▸ Compiling AnonymousDisposable.swift
▸ Compiling Switch.swift
▸ Compiling RefCount.swift
▸ Compiling Filter.swift
▸ Compiling ObserverType.swift
▸ Compiling Event.swift
▸ Compiling Zip.swift
▸ Compiling Zip+arity.swift
▸ Compiling SubscribeOn.swift
▸ Compiling Observable+Concurrency.swift
▸ Compiling Observable+StandardSequenceOperators.swift
▸ Compiling Debug.swift
▸ Compiling Observable+Debug.swift
▸ Compiling Reduce.swift
▸ Compiling Observable+Aggregate.swift
▸ Compiling Take.swift
▸ Compiling Observable+Time.swift
▸ Compiling Concat.swift
▸ Compiling Observable+Multiple.swift
▸ Compiling Observable+Binding.swift
▸ Compiling Do.swift
▸ Compiling Observable+Single.swift
▸ Compiling Amb.swift
▸ Compiling TakeWhile.swift
▸ Compiling Buffer.swift
▸ Compiling ObserveOnSerialDispatchQueue.swift
▸ Compiling Map.swift
▸ Compiling DelaySubscription.swift
▸ Compiling BehaviorSubject.swift
▸ Compiling Variable.swift
▸ Compiling FlatMap.swift
▸ Compiling Observable+Creation.swift
▸ Compiling Scan.swift
▸ Compiling Merge.swift
▸ Compiling Never.swift
▸ Compiling Observable.swift
▸ Compiling Producer.swift
▸ Compiling Repeat.swift
▸ Compiling StartWith.swift
▸ Compiling Range.swift
▸ Compiling CombineLatest+arity.swift
▸ Compiling CombineLatest+CollectionType.swift
▸ Compiling Sample.swift
▸ Compiling ObserveOn.swift
▸ Compiling Catch.swift
▸ Compiling Zip+CollectionType.swift
▸ Compiling Deferred.swift
▸ Compiling Generate.swift
▸ Compiling TakeUntil.swift
▸ Compiling Empty.swift
▸ Compiling Timer.swift
▸ Compiling Skip.swift
▸ Compiling FailWith.swift
▸ Compiling Just.swift
▸ Compiling TailRecursiveSink.swift
▸ Compiling ObservableType.swift
▸ Compiling SubjectType.swift
▸ Compiling InfiniteSequence.swift
▸ Compiling Queue.swift
▸ Compiling CurrentThreadScheduler.swift
▸ Compiling AsyncLock.swift
▸ Compiling ConnectableObservableType.swift
▸ Compiling AnonymousObserver.swift
▸ Compiling CombineLatest.swift
▸ Compiling ObserverOf.swift
▸ Compiling ObserverType+Extensions.swift
▸ Compiling Sink.swift
▸ Compiling NopDisposable.swift
▸ Compiling StableCompositeDisposable.swift
▸ Compiling DispatchQueueSchedulerPriority.swift
▸ Compiling DisposeBase.swift
▸ Compiling BinaryDisposable.swift
▸ Compiling RecursiveScheduler.swift
▸ Compiling MainScheduler.swift
▸ Compiling Rx.swift
▸ Compiling SerialDispatchQueueScheduler.swift
▸ Compiling SchedulerType.swift
▸ Compiling ScopedDisposable.swift
▸ Compiling Error.swift
▸ Compiling ScheduledDisposable.swift
▸ Compiling SerialDisposable.swift
▸ Compiling RxBox.swift
▸ Compiling DisposeBag.swift
▸ Compiling ScheduledItem.swift
▸ Compiling Lock.swift
▸ Compiling ImmediateSchedulerType.swift
▸ Compiling Disposable.swift
▸ Compiling OperationQueueScheduler.swift
▸ Compiling SingleAssignmentDisposable.swift
▸ Compiling SchedulerServices+Emulation.swift
▸ Compiling CompositeDisposable.swift
▸ Compiling Bag.swift
▸ Compiling NAryDisposable.swift
▸ Compiling Cancelable.swift
▸ Compiling ConcurrentDispatchQueueScheduler.swift
▸ Compiling NopDisposable.swift
▸ Compiling StableCompositeDisposable.swift
▸ Compiling DispatchQueueSchedulerPriority.swift
▸ Compiling DisposeBase.swift
▸ Compiling BinaryDisposable.swift
▸ Compiling RecursiveScheduler.swift
▸ Compiling MainScheduler.swift
▸ Compiling Rx.swift
▸ Compiling SerialDispatchQueueScheduler.swift
▸ Compiling SchedulerType.swift
▸ Compiling ScopedDisposable.swift
▸ Compiling Error.swift
▸ Compiling ScheduledDisposable.swift
▸ Compiling SerialDisposable.swift
▸ Compiling RxBox.swift
▸ Compiling DisposeBag.swift
▸ Compiling ScheduledItem.swift
▸ Compiling Lock.swift
▸ Compiling ImmediateSchedulerType.swift
▸ Compiling Disposable.swift
▸ Compiling OperationQueueScheduler.swift
▸ Compiling SingleAssignmentDisposable.swift
▸ Compiling SchedulerServices+Emulation.swift
▸ Compiling CompositeDisposable.swift
▸ Compiling Bag.swift
▸ Compiling NAryDisposable.swift
▸ Compiling Cancelable.swift
▸ Compiling ConcurrentDispatchQueueScheduler.swift
▸ Touching RxSwift.framework
▸ Building Rx/RxBlocking-watchOS [Release]
▸ Compiling Observable+Blocking.swift
▸ Touching RxBlocking.framework
▸ Building RxTests/RxTests-watchOS [Release]
▸ Compiling Observable+ConcurrencyTest.swift

⌦  /Users/bontoJR/Workspace/RxSwift/RxTests/RxSwiftTests/Tests/Observable+ConcurrencyTest.swift:10:8: no such module 'XCTest'

import XCTest
       ^


▸ Compiling RxTest.swift

⌦  /Users/bontoJR/Workspace/RxSwift/RxTests/RxSwiftTests/Tests/Observable+ConcurrencyTest.swift:10:8: no such module 'XCTest'

import XCTest
```

**Comment by bontoJR** [comment]
It works on my device, so I think it can be imported in develop @kzaher

**Comment by kzaher** [comment]
@cfraz89 Could you please target this PR to develop branch so we can merge it :)

**Comment by kzaher** [comment]
And I think we'll need to delete `RxTests-watchOS.xcscheme` and `RxTests-watchOS` before merge because watchOS doesn't support tests :(

**Comment by bontoJR** [comment]
Bump @cfraz89 !

**Comment by cfraz89** [comment]
Roger that. I'll delete tests and reopen against develop.

**Pull request closed without merging**
