### PR TITLE
Adds two rx properties to Cocoa controls.

### PR DESCRIPTION
**Pull request by mrahmiao**
1. Adds `rx_enabled` to `NSControl`
2. Adds `rx_state` to `NSButton`

### CODE REVIEW

**Comment by mrahmiao** [comment]
@kzaher Not sure why CI always failed with the log

> ERROR: line `//` is invalid: //  Copyright © (\d+) Krunoslav Zaher. All rights reserved.
     while Validating RxCocoaTests/NSControl+RxTests.swift

And I've got hundreds of errors in my local project while testing with *AllTests-OSX* such as:

> Use of undeclared type 'TestableObservable'

**Comment by kzaher** [comment]
Hi @mrahmiao ,

After we add new commits/features to our repository https://github.com/ReactiveX/RxSwift those changes won't be reflected to yours automatically.

That's why you have those `TestableObservable`.
I believe you have to manually sync your branches (including `develop`) with ours. ¯\\\_(ツ)\_/¯ 
That is really bad UX IMHO, and hoping smart people at GitHub will find some way to improve this, because it's really horrible.

We have header validation tool running. It will validate that all headers are uniform. We run `./scripts/pre-release-tests.sh` on build server, and that scripts calls `scripts/validate-headers.swift`.

`scripts/validate-headers.swift` enforces standard header structure in project.

**Comment by mrahmiao** [comment]
Hi @kzaher ,
All changes should have been pulled from the original repository https://github.com/ReactiveX/RxSwift to my local repo. And it just passed all the tests and I have done nothing. Weird~

**Comment by kzaher** [comment]
Cool :)

**Pull request merged**
