### PR TITLE
Fix Demo: Filtering and Conditional Operators

### PR DESCRIPTION
**Pull request by bshewmak**
Changed `.subscribe` to `.subscribeNext` to alleviate error put in debug console.

**Before Change:**

> --- single example ---
> 🐱
> 
> --- single with conditions example ---
> **Error(Sequence doesn't contain any elements.)**

**After Change:**

> --- single example ---
> 🐱
> 
> --- single with conditions example ---
> 
> --- take example ---

Now, no **Error** with assumed output of empty. 

Also, this is my first pull request. So please, any advice as well as insight into things I did wrong in _this_ process would be appreciated.

Cheers, 
Ben

### CODE REVIEW

**Comment by scotteg** [comment]
Hi @bshewmak, thanks for bringing this up 🙂. I think a benefit of the example as is is that it demonstrates if the sequence does not emit any elements that meet the condition, an error is emitted instead. But I realize now that it would be better to add another example (before this one) with a condition that demonstrates when one of the elements meets the condition (e.g., `.single { $0 == "🐱" }`. Would you like to make that change?

**Comment by bshewmak** [comment]
Sure I would love to :). Would you like me to leave the "error" example or leave that change too? 

Regards,
Ben

**Comment by scotteg** [comment]
@bshewmak Hi Ben, maybe include a successful example, an error due to repeating elements, and an error due to no elements, such as this:

```
example("single with conditions") {
    let disposeBag = DisposeBag()
    
    Observable.of("🐱", "🐰", "🐶")
        .single { $0 == "🐱" }
        .subscribe { print($0) }
        .addDisposableTo(disposeBag)
    
    Observable.of("🐱", "🐰", "🐶", "🐱", "🐰", "🐶")
        .single { $0 == "🐱" }
        .subscribe { print($0) }
        .addDisposableTo(disposeBag)
    
    Observable.of("🐸", "🐷", "🐵")
        .single { $0 == "🔵" }
        .subscribe { print($0) }
        .addDisposableTo(disposeBag)
}

--- single with conditions example ---
Next(🐱)
Completed
Next(🐱)
Error(Sequence contains more than one element.)
Error(Sequence doesn't contain any elements.)
```

**Comment by scotteg** [comment]
Hi @bshewmak, do you want to submit this PR? No worries if you're busy, I can do it. Just let me know and thanks again for raising this issue. 🙂

**Comment by bshewmak** [comment]
Hey @scotteg! I apologize for not getting back to you. I started my new job two weeks ago and have been busy as you can imagine making the transition. I would love to submit a pull request with the new additions / changes. Give me a couple of days and I hope to have something of quality to submit to you :).

**Comment by scotteg** [comment]
@bshewmak Ok, sounds good. No rush and congrats on the new job!

**Comment by bshewmak** [comment]
@scotteg Thank you, now the real fun begins. Per your suggestion, I've updated the example to include the three examples total (two additional). I tried to maintain consistency with respect to the rest of the playground page. I am still fairly new in the **Rx** world, **RxSwift** being my first taste of using it. This playground was extremely helpful.

**Pull request merged**
