### PR TITLE
Fix CI build by updating jazzy config

### PR DESCRIPTION
**Pull request by devxoul**
It breaks recent pull requests 🤔 Not sure which branch is suitable for this PR. Please change the target branch if needed.

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @devxoul ,

I'm a bit confused, which PRs are you referring to?

**Comment by devxoul** [comment]
@kzaher, I saw some builds (#1432, #1435) are failing with an error message:

> Please run ./scripts/update-jazzy-config.rb

I thought it was the problem but it doesn't seem to be the solution 🤔

**Comment by kzaher** [comment]
@devxoul I think this they need to run this for their own PRs.

**Comment by kerimsari** [comment]
Hi @devxoul,

I've got an error that says "Please run ./scripts/update-jazzy-config.rb" every time i run ./scripts/all-tests.sh in the main branch with .jazzy.yml file updated as below.

What should i do to run to be able to run ./scripts/all-tests.sh successfully?

---
custom_categories:
- name: RxCocoa/Common
  children:
  - ControlTarget
  - DelegateProxy
  - DelegateProxyType
  - Infallible+Bind
  - Observable+Bind
  - RxCocoaObjCRuntimeError+Extensions
  - RxTarget
  - SectionedViewDataSourceType
  - TextInput
- name: RxCocoa/Foundation
  children:
  - KVORepresentable+CoreGraphics
  - KVORepresentable+Swift
  - KVORepresentable
  - NSObject+Rx+KVORepresentable
  - NSObject+Rx+RawRepresentable
  - NSObject+Rx
  - NotificationCenter+Rx
  - URLSession+Rx
- name: RxCocoa/Platform
  children:
  - DispatchQueue+Extensions
- name: RxCocoa
  children:
  - RxCocoa
- name: RxCocoa/Traits
  children:
  - ControlEvent
  - ControlProperty
- name: RxCocoa/Traits/Driver
  children:
  - BehaviorRelay+Driver
  - ControlEvent+Driver
  - ControlProperty+Driver
  - Driver+Subscription
  - Driver
  - Infallible+Driver
  - ObservableConvertibleType+Driver
- name: RxCocoa/Traits/SharedSequence
  children:
  - ObservableConvertibleType+SharedSequence
  - SchedulerType+SharedSequence
  - SharedSequence+Concurrency
  - SharedSequence+Operators+arity
  - SharedSequence+Operators
  - SharedSequence
- name: RxCocoa/Traits/Signal
  children:
  - ControlEvent+Signal
  - ObservableConvertibleType+Signal
  - PublishRelay+Signal
  - Signal+Subscription
  - Signal
- name: RxCocoa/iOS/DataSources
  children:
  - RxCollectionViewReactiveArrayDataSource
  - RxPickerViewAdapter
  - RxTableViewReactiveArrayDataSource
- name: RxCocoa/iOS/Events
  children:
  - ItemEvents
- name: RxCocoa/iOS
  children:
  - NSTextStorage+Rx
  - UIActivityIndicatorView+Rx
  - UIApplication+Rx
  - UIBarButtonItem+Rx
  - UIButton+Rx
  - UICollectionView+Rx
  - UIControl+Rx
  - UIDatePicker+Rx
  - UIGestureRecognizer+Rx
  - UINavigationController+Rx
  - UIPickerView+Rx
  - UIRefreshControl+Rx
  - UIScrollView+Rx
  - UISearchBar+Rx
  - UISearchController+Rx
  - UISegmentedControl+Rx
  - UISlider+Rx
  - UIStepper+Rx
  - UISwitch+Rx
  - UITabBar+Rx
  - UITabBarController+Rx
  - UITableView+Rx
  - UITextField+Rx
  - UITextView+Rx
  - WKWebView+Rx
- name: RxCocoa/iOS/Protocols
  children:
  - RxCollectionViewDataSourceType
  - RxPickerViewDataSourceType
  - RxTableViewDataSourceType
- name: RxCocoa/iOS/Proxies
  children:
  - RxCollectionViewDataSourcePrefetchingProxy
  - RxCollectionViewDataSourceProxy
  - RxCollectionViewDelegateProxy
  - RxDelegateProxyCrashFix
  - RxNavigationControllerDelegateProxy
  - RxPickerViewDataSourceProxy
  - RxPickerViewDelegateProxy
  - RxScrollViewDelegateProxy
  - RxSearchBarDelegateProxy
  - RxSearchControllerDelegateProxy
  - RxTabBarControllerDelegateProxy
  - RxTabBarDelegateProxy
  - RxTableViewDataSourcePrefetchingProxy
  - RxTableViewDataSourceProxy
  - RxTableViewDelegateProxy
  - RxTextStorageDelegateProxy
  - RxTextViewDelegateProxy
  - RxWKNavigationDelegateProxy
- name: RxCocoa/macOS
  children:
  - NSButton+Rx
  - NSControl+Rx
  - NSSlider+Rx
  - NSTextField+Rx
  - NSTextView+Rx
  - NSView+Rx
- name: RxRelay
  children:
  - BehaviorRelay
  - Observable+Bind
  - PublishRelay
  - ReplayRelay
  - Utils
- name: RxSwift
  children:
  - AnyObserver
  - Binder
  - Cancelable
  - ConnectableObservableType
  - Date+Dispatch
  - Disposable
  - Errors
  - Event
  - GroupedObservable
  - ImmediateSchedulerType
  - Observable+Concurrency
  - Observable
  - ObservableConvertibleType
  - ObservableType+Extensions
  - ObservableType
  - ObserverType
  - Reactive
  - Rx
  - RxMutableBox
  - SchedulerType
- name: RxSwift/Concurrency
  children:
  - AsyncLock
  - Lock
  - LockOwnerType
  - SynchronizedDisposeType
  - SynchronizedOnType
  - SynchronizedUnsubscribeType
- name: RxSwift/Disposables
  children:
  - AnonymousDisposable
  - BinaryDisposable
  - BooleanDisposable
  - CompositeDisposable
  - Disposables
  - DisposeBag
  - DisposeBase
  - NopDisposable
  - RefCountDisposable
  - ScheduledDisposable
  - SerialDisposable
  - SingleAssignmentDisposable
  - SubscriptionDisposable
- name: RxSwift/Extensions
  children:
  - Bag+Rx
- name: RxSwift/Observables
  children:
  - AddRef
  - Amb
  - AsMaybe
  - AsSingle
  - Buffer
  - Catch
  - CombineLatest+Collection
  - CombineLatest+arity
  - CombineLatest
  - CompactMap
  - Concat
  - Create
  - Debounce
  - Debug
  - Decode
  - DefaultIfEmpty
  - Deferred
  - Delay
  - DelaySubscription
  - Dematerialize
  - DistinctUntilChanged
  - Do
  - ElementAt
  - Empty
  - Enumerated
  - Error
  - Filter
  - First
  - Generate
  - GroupBy
  - Just
  - Map
  - Materialize
  - Merge
  - Multicast
  - Never
  - ObserveOn
  - Optional
  - Producer
  - Range
  - Reduce
  - Repeat
  - RetryWhen
  - Sample
  - Scan
  - Sequence
  - ShareReplayScope
  - SingleAsync
  - Sink
  - Skip
  - SkipUntil
  - SkipWhile
  - StartWith
  - SubscribeOn
  - Switch
  - SwitchIfEmpty
  - Take
  - TakeLast
  - TakeWithPredicate
  - Throttle
  - Timeout
  - Timer
  - ToArray
  - Using
  - Window
  - WithLatestFrom
  - WithUnretained
  - Zip+Collection
  - Zip+arity
  - Zip
- name: RxSwift/Observers
  children:
  - AnonymousObserver
  - ObserverBase
  - TailRecursiveSink
- name: RxSwift/Platform
  children:
  - AtomicInt
  - DispatchQueue+Extensions
  - Platform.Darwin
  - Platform.Linux
  - RecursiveLock
- name: RxSwift/Platform/DataStructures
  children:
  - Bag
  - InfiniteSequence
  - PriorityQueue
  - Queue
- name: RxSwift/Schedulers
  children:
  - ConcurrentDispatchQueueScheduler
  - ConcurrentMainScheduler
  - CurrentThreadScheduler
  - HistoricalScheduler
  - HistoricalSchedulerTimeConverter
  - MainScheduler
  - OperationQueueScheduler
  - RecursiveScheduler
  - SchedulerServices+Emulation
  - SerialDispatchQueueScheduler
  - VirtualTimeConverterType
  - VirtualTimeScheduler
- name: RxSwift/Schedulers/Internal
  children:
  - DispatchQueueConfiguration
  - InvocableScheduledItem
  - InvocableType
  - ScheduledItem
  - ScheduledItemType
- name: RxSwift/Subjects
  children:
  - AsyncSubject
  - BehaviorSubject
  - PublishSubject
  - ReplaySubject
  - SubjectType
- name: RxSwift/SwiftSupport
  children:
  - SwiftSupport
- name: RxSwift/Traits/Infallible
  children:
  - Infallible+CombineLatest+arity
  - Infallible+Concurrency
  - Infallible+Create
  - Infallible+Operators
  - Infallible+Zip+arity
  - Infallible
  - ObservableConvertibleType+Infallible
- name: RxSwift/Traits/PrimitiveSequence
  children:
  - Completable+AndThen
  - Completable
  - Maybe
  - ObservableType+PrimitiveSequence
  - PrimitiveSequence+Concurrency
  - PrimitiveSequence+Zip+arity
  - PrimitiveSequence
  - Single

**Comment by freak4pc** [comment]
This PR is 5 years old. Would be better to open a new issue with your problem :)

**Pull request closed without merging**
