### PR TITLE
Add macOS NSPopUpButton reactive extensions

### PR DESCRIPTION
**Pull request by fpillet**
Reactive extensions for NSPopUpButton on macOS, with tests.

### CODE REVIEW

**Comment by freak4pc** [comment]
Just FYI you could've just changed the branch without a new PR :) 
0843def8-0ecd-4683-a0e2-c473134f54f7

**Comment by fpillet** [comment]
That would have done it 👍  next time!

**Comment by kzaher** [comment]
Hi guys,

I've tried to review this PR as best as I can, but it took a while since I don't have any experience with OSX.

The current behavior of `menuItems` now clears selection every time on bind. Yes, we could create some hacks how to not clear it, but it seems to me that conceptually setting `menuItems` should be coupled with setting `selectedItemIndex`. Those 2 values together make control state. Something like `public var menuItems: UIBindingObserver<Base, (selectedItemIndex: Int, titles: [String])>`. Otherwise you are depending on binding items and selected index in correct order which is prone to errors and current interface doesn't communicate this is a requirement.

I'm not sure is there any value in having `public var selectedItem: ControlProperty<NSMenuItem?>`.  `NSMenuItem` is not a value type so it's not an ideal sequence element and it seems to me that using a tag as unique identifier is far from ideal since it's an Int and not a generic identifier. As far as I can tell `selectedItemIndex` + access to data model of the items that are being bound to `NSPopUpButton` is the only consistent way to determine the typed selected item. I'm in favor of not including this API.

It seems to me that `public var selectedItemTitle: ControlProperty<String?>` API is depending on the title of the item, which is not a robust way to differentiate between two items, especially when drop down is populated with user generated content. I'm in favor of not including this API.

Reasoning for not including`public var selectedItemTag: ControlProperty<Int?>` is similar to `selectedItemTitle`. I don't think it's a generic way to differentiate between items and it seems to me that knowledge of `selectedItemIndex` + access to data model of the items that are being bound to `NSPopUpButton` is the only consistent way to determine the typed selected item.

It seems to me that `public func menuItems() -> UIBindingObserver<Base, [String]>` and `public func menuItemsWithTags() -> UIBindingObserver<Base, [(String,Int)]>` should be merged into something like `public var menuItems: UIBindingObserver<Base, (selectedItemIndex: Int, titles: [String])>` because of similar reasons. Tags aren't generic enough, Apple probably added them as a crotch.

Hope my explanations make sense.

**Comment by fpillet** [comment]
Too much hassle, not sharing this anymore as I need it in my own projects.

**Pull request closed without merging**
