### PR TITLE
Add distinct operator to ObservableType

### PR DESCRIPTION
**Pull request by SiarheiFedartsou**
Hi! I was surprised that there is still no `distinct` operator in RxSwift and decided to fill this gap.

### CODE REVIEW

**Comment by carlosypunto** [comment]
Hi, @SiarheiFedartsou, maybe you don't know about [RxSwiftExt: A collection of Rx operators & tools not found in the core RxSwift distribution](https://github.com/RxSwiftCommunity/RxSwiftExt), there you can found [distinct operator](https://github.com/RxSwiftCommunity/RxSwiftExt/blob/master/Source/RxSwift/distinct.swift)

**Comment by carlosypunto** [comment]
@SiarheiFedartsou thanks for your effort. But, as you can see in the intention of that repository, the RxSwift core is being intentionally kept as compact as possible to avoid bloat. In any case, the big contributors and members, may they want to give you another answer.

**Comment by SiarheiFedartsou** [comment]
@carlosypunto yes, I really didn’t know about RxSwiftExt, but almost all other ReactiveX implementations have such operator by default.

**Comment by SiarheiFedartsou** [comment]
@kzaher what do you think?

**Comment by kzaher** [comment]
@SiarheiFedartsou I agree with everything @carlosypunto said. 

We would need a really good reason why we would want to include some operator in this repo.

**Pull request closed without merging**
