### PR TITLE
Add from operators to SharedSequence

### PR DESCRIPTION
**Pull request by yuzushioh**
Hi! I added `from` operators to SharedSequence in this PR.

### Added operators
- from(_ array:)
- from(_ sequence:)
- from(optional:)

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @yuzushioh ,

Could you please add tests to `Driver+Test.swift`.

**Comment by yuzushioh** [comment]
Hi @kzaher I added some tests for operators I added👍

**Comment by kzaher** [comment]
I've merged this manually, github didn't track the merge because I've done a rebase.

**Comment by yuzushioh** [comment]
Ok! Thank you for fixing unit tests🙏🏻

**Pull request closed without merging**
