### PR TITLE
Fix Swift 4 build failure on Travis

### PR DESCRIPTION
**Pull request by devxoul**
Update swiftenv script to use `4.0-DEVELOPMENT-SNAPSHOT-2017-07-11-a` version. This is from `$ swiftenv install --list-snapshots | grep "4\.0" | tail -n 1`.

But still got an error:

```
/path/to/RxSwift/Sources/RxSwift/DispatchQueueConfiguration.swift:46:9:
error: value of type 'DispatchSourceTimer' has no member 'schedule'
```

You can simulate this error on https://swift.sandbox.bluemix.net/ too. (Settings > Select `Dev. 4.0` version)

```swift
import Dispatch

let queue = DispatchQueue.main
let deadline: DispatchTime = DispatchTime.now()
let leeway: DispatchTimeInterval = .seconds(1)

let timer = DispatchSource.makeTimerSource(queue: queue)
timer.schedule(deadline: deadline, leeway: leeway)
^~~~~ ~~~~~~~~
```

### CODE REVIEW

**Comment by devxoul** [comment]
It seems that there's a `schedule()` on Swift source: https://github.com/apple/swift/blob/swift-DEVELOPMENT-SNAPSHOT-2017-07-11-a/stdlib/public/SDK/Dispatch/Source.swift#L488-L491 🤔

**Comment by devxoul** [comment]
Added e6a1f5323734fe17bf1cfcad0b9182a6a5a3b988 (w/ @freak4pc @carlosypunto):

```diff
- timer.schedule(deadline: deadline, leeway: leeway)
+ timer.scheduleOneshot(deadline: deadline, leeway: leeway)

- timer.schedule(deadline: initial, repeating: dispatchInterval(period), leeway: leeway)
+ timer.scheduleRepeating(deadline: initial, interval: dispatchInterval(period), leeway: leeway)
```

I referred to https://github.com/apple/swift-corelibs-libdispatch/blob/swift-DEVELOPMENT-SNAPSHOT-2017-07-13-a/src/swift/Wrapper.swift#L290-L302.

**Comment by devxoul** [comment]
e6a1f5323734fe17bf1cfcad0b9182a6a5a3b988 could resolves the Linux build failure but Mac SPM build still fails: https://travis-ci.org/ReactiveX/RxSwift/jobs/254138516

```
LLVM ERROR: IO failure on output stream.
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/travis/build/ReactiveX/RxSwift/.build/release.yaml
```

I've googled with this error message and got these:

> You're most likely out of disk space. Where is your build folder located? It might not be allowed to write and causing that error.
> (https://stackoverflow.com/questions/12954006/apple-llvm-compiler-4-1-error)

> Ok. I finally got this to compile. It turns out that 8 Gb of disk space is not sufficient (don't ask me why). I deleted some old movies, and with 13 Gb, it compiled fine.
> (https://trac.macports.org/ticket/43389)

But last time I checked the disk space(https://travis-ci.org/devxoul/RxSwift/jobs/254141569) it seems that the machine had enough space for build.

```
Filesystem      Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk0s2   149Gi  120Gi   28Gi    81% 2791257 4292176022    0%   /
devfs          177Ki  177Ki    0Bi   100%     612          0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%       0          0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%       0          0  100%   /home
```

**Comment by kzaher** [comment]
Hi @devxoul ,

I've cleaned up 87.62 GB on my machine but it still fails when I run `swift build` in the root of RxSwift repo.

I've also done `rm -rf .build`.

**Pull request merged**
