### PR TITLE
Add elementAt operator to SharedSequence

### PR DESCRIPTION
**Pull request by yuzushioh**
Hi! I added `elementAt` operator to `SharedSequence` in this PR.

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @yuzushioh ,

could you maybe provide some context why do you need this operator on `SharedSequence`?

**Comment by yuzushioh** [comment]
Hi @kzaher 

In my ViewModel, I have a stored property `pagination` type of `Driver<Pagination>`. a type `Pagination` is a struct and  has properties such as `MaxSortId`. I want to extract a pagination for a specific page.  In most of my view models I use `Driver` instead of `Observable`

I am doing like this when I extract a pagination element for third page.

```swift
// Trigger is `Driver<Void>`
let extractedPagination = trigger.flatMap {  _ -> Driver<Pagination> in 
    let paginationObservable = pagination.asObservable().elementAt(2)
    return paginationObservable.asDriver(onErrorDriveWith: .empty())
}
```

Instead, it would be great if I can do

```swift
// Trigger is Driver<Void>
let extractedPagination = trigger.flatMap {  _ -> Driver<Pagination> in 
    return pagination.elementAt(2)
}
```

This is why I added `elementAt` operator to `SharedSequence`.

**Comment by kzaher** [comment]
Hi @yuzushioh ,

I'm not sure using `elementAt` is a good idea with `Driver`. `Driver` has `shareReplay` sharing strategy. That has a consequence that calculation could start from anywhere, and using `.elementAt(2)` could return you any element with index >= 2.

**Comment by yuzushioh** [comment]
Hi @kzaher 

I thought about it and you are right about this.
> using .elementAt(2) could return you any element with index >= 2.

I will think about other ways to do my thing. Thanks 👍

**Pull request closed without merging**
