### PR TITLE
Fix deployment target warnings in Xcode 14

### PR DESCRIPTION
**Pull request by keith**
Some platforms' deployment targets were lower than Xcode 14 supports, causing warnings. In this case I bumped to the minimum supported version.

### CODE REVIEW

**Comment by keith** [comment]
Maybe we shouldn't merge this depending on older Xcode version support

**Comment by freak4pc** [comment]
Thanks @keith, we can possibly push it to the next release:
> Please note, starting April 2023, all iOS and iPadOS apps submitted to the App Store must be built with Xcode 14.1 and the iOS 16.1 SDK.

**Comment by DivineDominion** [comment]
Ran into this by accident and noticed it's already April, so might be good for a point-release, soon? :)

**Comment by DivineDominion** [comment]
@freak4pc Thanks for merging -- and so quickly! I was looking at a day of work of changing repositories across dependencies otherwise :)

**Pull request merged**
