### PR TITLE
Added bindable backgroundColor property to UIView

### PR DESCRIPTION
**Pull request by BenchR267**
As already described in the title, I added a bindable property to UIView which makes it possible to bind other observables to that property.

### CODE REVIEW

**Comment by BenchR267** [comment]
Is anyone ever reviewing this?

**Comment by sergdort** [comment]
Hi @BenchR267 
I pretty sure your PR can be adressed [to this issue](https://github.com/ReactiveX/RxSwift/issues/361)

**Comment by BenchR267** [comment]
@sergdort so in short: there are only a few given bindably properties and everything else should be extended in the project?

**Comment by kzaher** [comment]
Hi @BenchR267 ,

I guess we need to think about how to define criteria what is considered an extension that we can support in RxCocoa and what isn't.

So far we've only included what I've considered basic data properties. It's not feasible to have one rx property for one UIKit property. 

I would like to either find some generic way to define those simple extensions or a simple rules that  limit the number of those extensions to some reasonable number.

I guess if there will be a lot of requests for some particular extension we can make exceptions.

**Comment by BenchR267** [comment]
@kzaher Thanks for the explanation, makes totally sense. One bindable rx property for every UIKit property is not maintainable :)

**Pull request closed without merging**
