### PR TITLE
Fix typo in README: s/exists/exits/

### PR DESCRIPTION
**Pull request by fastred**

### CODE REVIEW

**Comment by orta** [comment]
any chance you can make it `exits the` instead? The English feels nicer

**Comment by fastred** [comment]
@orta Good point! Done.

**Comment by orta** [comment]
great work

**Comment by kzaher** [comment]
I'll merge this back to `develop` branch. It's best to have unidirectional publish model :)

I'm sure we have tons of other errors in docs since I'm not a native speaker, so feel free to inform me of any frequent errors I'm making :), or feel free to just send PRs with better formulated sentences. All options are awesome.

**Comment by orta** [comment]
ergh, develop branches. Get 2.0.0 shipped :P

**Pull request merged**
