### PR TITLE
Do you still support iOS7?

### PR DESCRIPTION
**Pull request by acecilia**
By the way, I found [this](https://github.com/kylef/Hyperplay/tree/master/Pods/RxSwift) explanation very useful for adding RxSwift to my iOS7 project. I imagine that is an old file from RxSwift repo, but I could not find it or anything similar in the repo nowadays.

:)

### CODE REVIEW

**Comment by acecilia** [comment]
No way! Test passed in my machine..
I dont know how to interpret Travis output:
`Testing failed:
	Test target AllTests-iOS encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **
+++STATUS=65
+++set +x
65
The command "./scripts/pre-release-tests.sh" exited with 65.
Done. Your build exited with 1.
/Users/travis/build.sh: line 109: shell_session_update: command not found`

**Comment by acecilia** [comment]
OK, test passed now :)

**Comment by kzaher** [comment]
Hi @acecilia ,

we've had terrible experiences with Swift on iOS7 devices. We don't do any magic that should break on iOS7, but as far as I can tell Swift compiler doesn't produce correct code in some cases on iOS7 and that can cause weird crashes (especially with iPhone 5S).

**Comment by acecilia** [comment]
I know, I experienced it ;P I am using RxSwift with iOS7 right now and it seems to work. (with the fixes I included in this PR)

**Comment by kzaher** [comment]
Hi @acecilia ,

If you could target changes from this PR to `develop` branch, I would be happy to merge this.

**Comment by acecilia** [comment]
sure, 5 minutes :)

**Pull request closed without merging**
