### PR TITLE
Rename `take(_:scheduler:)` to `take(duration:scheduler:)` to disambiguate overloads

### LINKED ISSUE #1625: `take(_ duration:scheduler:)` and `take(_ count:)` usage ambiguity
There is a great confusion between `take(_ duration:scheduler:)` and `take(_ count:)` in the sense they both don't require a label for the first argument.

### take(_ duration:scheduler:) : 
https://github.com/ReactiveX/RxSwift/blob/f1e215a3fe1303568e415095cb00a6ca2a27b706/RxSwift/Observables/Take.swift#L41

### take(_ count:) :

https://github.com/ReactiveX/RxSwift/blob/f1e215a3fe1303568e415095cb00a6ca2a27b706/RxSwift/Observables/Take.swift#L19

I would suggest dropping the `_` from the duration variation, making it `take(duration:scheduler:)` to get rid of the ambiguity. 

This was noticed when @irace asked a question with an example that uses both of them in the same sequence, with code similar to this: 

```swift
observable
  .take(5)
  .take(8, scheduler: MainScheduler.instance)
```

There is no real way to know what the latter does. The "count" one makes sense to be label-less.

This can be done via either
1. Soft deprecating in a minor patch
2. Hard deprecating in next major
3. A combination of both (stepped deprecation)

Let me know your thoughts.

### PR DESCRIPTION
**Pull request by freak4pc**
Fixes #1625. 

I took a minor decision to already mark the old version with an `@available` clause given the fact this is a relatively low-impact method being rarely used, and given the code change extremely low-effort (just adding `duration:` to the call-site). 

Using something like `DeprecationWarner` here seems like an overkill but I can go that way if you feel you prefer it.

### CODE REVIEW

**Comment by freak4pc** [comment]
Would you also mind adding this before cutting the new release? @kzaher

**Comment by kzaher** [comment]
@freak4pc Sorry, didn't notice the PR early enough.

**Comment by kzaher** [comment]
Hi @freak4pc ,

I've checked out the PR. I think that because of this issue https://github.com/ReactiveX/RxSwift/issues/1472 we should immediately make the type of parameter name `duration` to `DispatchTimeInterval`.

**Comment by freak4pc** [comment]
Hey @kzaher 
I still think those are two entirely different changes. 

Even if we fix the signature to support DispatchTimeInterval, the rest of the methods won't. That would be a much more vast change.

**Comment by freak4pc** [comment]
Yeah so @kzaher I quickly went through it - There is no easy "clean" way to make this. 

You would need to have all SchedulerType(s) provide a `scheduleRelative` and `schedulePeriodic` that take a `DispatchTimeInterval` and also decide if we completely want to drop the `RxTimeInterval` alias to `TimeInterval` or support both in a backward compatible way. 

IMO this a **much more widespread** change that is really out of scope for this tiny fix. 

I'd love to do a separate PR for introducing `DispatchTimeInterval` but it needs more discussion and **much** more work.

**Comment by kzaher** [comment]
Hi @freak4pc ,

> You would need to have all SchedulerType(s) provide a scheduleRelative and schedulePeriodic that take a DispatchTimeInterval and also decide if we completely want to drop the RxTimeInterval alias to TimeInterval or support both in a backward compatible way.

Yes, we would need to add two new overloads and a default implementation for new methods so we don't break custom schedulers.

We would also need to reroute methods that use RxTimeInterval to use DispatchTimeInterval in current scheduler implementations.

Third step is adding operators that just use DispatchTimeInterval and deprecate RxTimeInterval.

 > IMO this a much more widespread change that is really out of scope for this tiny fix.

I would agree. But it doesn't seem to me that it makes sense to deprecate the same API twice. Especially since we are already have #1472 reported.

**Comment by freak4pc** [comment]
@kzaher I see. I just think landing a PR of that vast of a change would take much more work, as well as reviewing that sort of change. Would definitely look into it though. 

I would be OK with a double deprecation, as changing all schedulers will take much longer. But If you feel strongly about this, I prefer closing this PR for now as it will not be relevant.

**Comment by kzaher** [comment]
Hi @freak4pc ,

I can also make the scheduler change. It doesn't seem to me like that big of a change at the moment, but I might be wrong. I can check it out in a couple of days.

**Comment by freak4pc** [comment]
Thanks @kzaher 
I tired playing with it a bit but TBH feel like I'm dropping right into the rabbit hole :) 
Schedulers are so deeply rooted and even though I know most of the system pretty well, I don't know Scheduler implementation that well. 

Also these kind of notes leave me worried of touching this: 😂 
```
// TODO:
// This looks horrible, and yes, it is.
```

**Comment by freak4pc** [comment]
@kzaher I vote for closing this for now until you have time to look into redoing Schedulers. I don't think me doing them would be good since I really don't 100% understand the underlying implementation and its a really low-level concept to RxSwift.

**Pull request closed without merging**
