### PR TITLE
Use rx_event instead of Selector

### PR DESCRIPTION
**Pull request by pixyzehn**
Replace Selector with rx_event in RxExample-iOS.

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @pixyzehn ,

I think the proposed changes are ok. Could you make the same ones for `GitHubSignupViewController2`, or do you want me to merge only these changes?

**Comment by pixyzehn** [comment]
@kzaher 
Of course. I'll make the same ones. I want you to merge `GitHubSignupViewController2`'s change.

**Comment by pixyzehn** [comment]
I included the two changes in this commit.

**Comment by kzaher** [comment]
Cool, thnx.

**Pull request merged**
