### PR TITLE
Make all frameworks MACH_O_TYPE staticlib

### PR DESCRIPTION
**Pull request by freak4pc**

### CODE REVIEW

**Comment by freak4pc** [comment]
@kzaher The failure seems to stem from the playground validation script. Seems like a nasty Swift compiler issue but I'm not sure.

Any thoughts? (reproduces locally as well)

```
Apple Swift version 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)
Target: x86_64-apple-macosx10.10
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -interpret build/Build/Products/Release/all-playground-pages.swift -target x86_64-apple-macosx10.10 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -F build/Build/Products/Release -D NOT_IN_PLAYGROUND -color-diagnostics -module-name main
build/Build/Products/Release/all-playground-pages.swift:992:10: warning: 'skipWhileWithIndex' is deprecated: Please use enumerated().skipWhile().map()
        .skipWhileWithIndex { element, index in
         ^
build/Build/Products/Release/all-playground-pages.swift:992:10: warning: 'skipWhileWithIndex' is deprecated: Please use enumerated().skipWhile().map()
        .skipWhileWithIndex { element, index in
         ^
Stack dump:
0.	Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -interpret build/Build/Products/Release/all-playground-pages.swift -target x86_64-apple-macosx10.10 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -F build/Build/Products/Release -D NOT_IN_PLAYGROUND -color-diagnostics -module-name main
0  swift                    0x0000000107635ee3 PrintStackTraceSignalHandler(void*) + 51
1  swift                    0x00000001076356bc SignalHandler(int) + 348
2  libsystem_platform.dylib 0x00007fff75252b5d _sigtramp + 29
3  libsystem_platform.dylib 0x0000000000000009 _sigtramp + 2329597129
4  libsystem_platform.dylib 0x000000010d10a01a _sigtramp + 2548790490
5  swift                    0x0000000103ecd19d llvm::MCJIT::runFunction(llvm::Function*, llvm::ArrayRef<llvm::GenericValue>) + 365
6  swift                    0x0000000103ed3572 llvm::ExecutionEngine::runFunctionAsMain(llvm::Function*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, char const* const*) + 1090
7  swift                    0x000000010349c5d1 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 58913
8  swift                    0x000000010348a6de swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 6862
9  swift                    0x00000001034287be main + 1246
10 libdyld.dylib            0x00007fff7506d3d5 start + 1
11 libdyld.dylib            0x0000000000000010 start + 2331585596
./scripts/validate-playgrounds.sh: line 8: 12778 Segmentation fault: 11  swift -v -D NOT_IN_PLAYGROUND -target x86_64-apple-macosx10.10 -F ${BUILD_DIRECTORY}/Build/Products/${configuration} ${PAGES_PATH}
```

**Comment by kzaher** [comment]
Ugh, maybe simply changing the type isn't enough.

**Comment by freak4pc** [comment]
I opened a bug in Swift Compiler, lets leave this open for now.

**Comment by kzaher** [comment]
@freak4pc Can we even use static libraries in playgrounds?

**Comment by freak4pc** [comment]
I'm not sure, but I wouldn't expect this kind of crash from swiftc, so the existence of a segmentation failure is a compiler bug.

**Comment by freak4pc** [comment]
@kzaher from Xcode 10.2 release notes: 

> Linking against a static Swift library might create a binary with missing type metadata because the object files that define the metadata inside the static archive are mistakenly considered unused. (47598583)
>
> This can manifest as a Swift runtime error with a message such as: “failed to demangle superclass of MyClass from mangled name ‘<mangled name>’”.
> 
> **Workaround**: If you can rebuild the static library, try building it with whole module optimization enabled. Otherwise, add -all_load to the linker flags in the client binary to ensure all object files are linked into it.

We can't fix this until a newer version of Xcode comes along and fixes this issue, so it seems. 

The workaround doesn't seem to work (we already use WMO and there's no binary client to try `-all_load` on)

**Comment by kzaher** [comment]
I will never understand what is wrong with them when they put these kinds of messages in the release notes:
> Linking against a static Swift library might create a binary with missing type metadata because the object files that define the metadata inside the static archive are mistakenly considered unused. (47598583)

> This can manifest as a Swift runtime error with a message such as: “failed to demangle superclass of MyClass from mangled name ‘’”.

> Workaround: If you can rebuild the static library, try building it with whole module optimization enabled. Otherwise, add -all_load to the linker flags in the client binary to ensure all object files are linked into it.

1rst This is a major issue.
2nd They knew about it and decided to release with it anyway.
3rd They know of a workaround but they didn't turn on `-all_load` by default in the compiler as a workaround but expect for everyone to turn on this flag manually.

One .... huge .... wtf?

I can't the mental process behind somebody putting this in the release notes and thinking this is fine.

**Pull request closed without merging**
