### PR TITLE
Added tvOS specific extension for UIButton

### PR DESCRIPTION
**Pull request by larslockefeer**
This is a clone or PR #242, now pointed at the `develop` branch.

### CODE REVIEW

**Comment by kzaher** [comment]
Hey @larslockefeer ,

Merging this...

I think I'll rename `rx_tap` to `rx_primaryAction` after merge and add it to unit tests :) I think `rx_primaryAction` probably describes this better :)

Hope that makes sense.

**Comment by larslockefeer** [comment]
@kzaher I have also been thinking about the name. For me as an iOS developer, I think `rx_tap` makes sense since this is the way you think about interacting with a `UIButton`. But for people doing `tvOS` only (which eventually will exist), `rx_primaryAction` will probably be better. Just like we don't talk about clicks on iOS like we do on OS X.

Trade offs :smile:

**Comment by kzaher** [comment]
For OSX I have no idea what to use :)

I tap on everything on my laptop, some people click on everything :) I think we'll probably go with `rx_action` on OSX. What a mess :)

**Comment by yury** [comment]
`rx_action`!

**Pull request merged**
