### PR TITLE
Disable bitcode to fix code signing with macOS 11.0 SDK

### LINKED ISSUE #2263: Xcode 12.2: RxCocoa code signing fails for macOS application
**Short description of the issue**:

Building and running macOS applications using RxCocoa works fine. After making a release build, though, the code signing step before submitting the app for notarization fails.

I made a little test project that shows this:

https://github.com/DivineDominion/RxTestApp

    git clone --recursive https://github.com/DivineDominion/RxTestApp.git

I also know a resolution and will propose a PR to fix this. It seems bitcode & arm64 don't mix with macOS SDK 11, thanks @matteorattotti for the hint

**Expected outcome**:

The app archive can be signed and submitted for notarization.

**What actually happens**:

`/RxCocoa.framework/Versions/A: code object is not signed at all`

more verbose output

```
2020-12-07 15:10:49 +0000  Running /usr/bin/codesign '-vvv' '--force' '--sign' 'F1C8B9C025AADFD0F5A1C94704B713AE48E05B2D' '--entitlements' '/var/folders/62/8k21681d08z9lhq8h433z3rh0000gp/T/XcodeDistPipeline.~~~30iivY/entitlements~~~AkwhDT' '--preserve-metadata=identifier,flags,runtime' '--requirements' '=designated => anchor apple generic  and identifier "$self.identifier" and ((cert leaf[field.1.2.840.113635.100.6.1.9] exists) or ( certificate 1[field.1.2.840.113635.100.6.2.6] exists and certificate leaf[field.1.2.840.113635.100.6.1.13] exists  and certificate leaf[subject.OU] = "FRMDA3XRGC" ))' '/var/folders/62/8k21681d08z9lhq8h433z3rh0000gp/T/XcodeDistPipeline.~~~30iivY/Root/Applications/RxTestApp.app/Contents/Frameworks/RxCocoa.framework/Versions/A'
2020-12-07 15:10:49 +0000  /var/folders/62/8k21681d08z9lhq8h433z3rh0000gp/T/XcodeDistPipeline.~~~30iivY/Root/Applications/RxTestApp.app/Contents/Frameworks/RxCocoa.framework/Versions/A: replacing existing signature
2020-12-07 15:10:49 +0000  /var/folders/62/8k21681d08z9lhq8h433z3rh0000gp/T/XcodeDistPipeline.~~~30iivY/Root/Applications/RxTestApp.app/Contents/Frameworks/RxCocoa.framework/Versions/A: code object is not signed at all
2020-12-07 15:10:49 +0000  /usr/bin/codesign exited with 1
```

**Self contained code example that reproduces the issue**:

https://github.com/DivineDominion/RxTestApp

    git clone --recursive https://github.com/DivineDominion/RxTestApp.git

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

Current HEAD, `61e9cff0613854430cbd252f66883b1f4fb0892d`

**Platform/Environment**

  - [ ] iOS
  - [x] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
Version 12.2 (12B45b)
```

**Installation method**:
  - [ ] CocoaPods (didn't test)
  - [x] Carthage
  - [x] Git submodules

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (Xcode 12.2, Xcode 12.3, Xcode 10.2)
  - [ ] no

**Level of RxSwift knowledge**:

  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

### PR DESCRIPTION
**Pull request by DivineDominion**
Closes #2263

I added a conditional `ENABLE_BITCODE=NO` for macOS SDK 11.0. This was the least invasive thing I could do.

Again, credit goes to @matteorattotti for figuring this out

Honesly, I'd prefer to just set `ENABLE_BITCODE=NO` in general (or for macOS in general), and be done with it for SDK 11.1, 11.2, ... as well.

What do y'all think?

---

My failing sample app comes with a `fix` branch that you can check out so see it works:

    git clone --recursive --branch fix https://github.com/DivineDominion/RxTestApp.git 

----

Until this is merged, for people using the `carthage.sh` build script, add this line to fix the issue:

```
# add this:
echo 'ENABLE_BITCODE = NO' >> $xcconfig

# before this (unchanged)
export XCODE_XCCONFIG_FILE="$xcconfig"
carthage "$@"
```

### CODE REVIEW

**Comment by DivineDominion** [comment]
Oh, I'm not sure what the generated CocoaPods project looks like and will report once I check that out.

**Comment by DivineDominion** [comment]
I can verify that CocoaPods installation does not produce the problem on `HEAD@main` at all because the generated Pods Xcode project doesn't contain `ENABLE_BITCODE` at all. (And it's not set to YES by system default; that's NO)

To test this on your machine, check out the cocoapods branch of my test repo:

   git clone --recursive --branch cocoapods https://github.com/DivineDominion/RxTestApp.git 


I believe it's safe to delete the `ENABLE_BITCODE` customizations completely for Carthage users. But belief isn't proof, and I'm not sure who ever needed this to be enabled.

**Comment by freak4pc** [comment]
> Oh, I'm not sure what the generated CocoaPods project looks like and will report once I check that out.

Thanks for looking into this!
SPM and CocoaPods don't rely at all on project settings so they should not be affected.
The only affected party is Carthage. 

I think I'm ok with disabling bitcode in the project altogether given that. It does seem CI is failing, though, so let me know if you can look into that.

Thanks again.

**Comment by DivineDominion** [comment]
@freak4pc I went ahead and removed the bitcode setting. I'm absolutely no expert with CI, so maybe we should ask someone more knowledgeable about what's going on, but I'll have a look!

**Comment by DivineDominion** [comment]
Looks like the timed-out CI runs now pass 🎉

**Review by freak4pc — APPROVED** [review]

**Pull request merged**
