### PR TITLE
[WIP] adds support for tvOS in RxCocoa

### PR DESCRIPTION
**Pull request by orta**
I don't know if I'll find the time to actually do whatever tests might be needed for this, and whatever is needed for carthage, or for anyone not using [CocoaPods-ExpertDifficulty](https://github.com/orta/cocoapods-expert-difficulty). So when someone decides to do this properly, this is the code you need.

### CODE REVIEW

**Comment by orta** [comment]
Looks like there's a lot of whitespace changes in here too, would recommend ticking "automatically trim trainmen whitespace" in Xcode

screen shot 2015-09-22 at 10 45 40

**Comment by orta** [comment]
This is a dupe! #149

**Comment by orta** [comment]
This is not a dupe!

**Comment by kzaher** [comment]
Oh damn it :/,

I think I'll need to turn this on because if somebody has that option it will mess up the whitespace, argh...

**Pull request merged**
