### PR TITLE
Rename Units to Traits & Update documentation for Single, Completable & Maybe

### PR DESCRIPTION
**Pull request by freak4pc**
Based on a discussion in the RxSwift Slack channel between myself and @kzaher , We’ve come to a conclusion the term Unit doesn’t properly describe what Driver, Single, Maybe & Completable are, which is some sort of a Variation of Observable, or - a Trait. 

For that reason this PR aims at renaming Units to Traits wherever it’s applicable, and also updating the Docs for those, as well as missing documentation for the new Traits (Single, Completable, Maybe) that didn’t have any.

Would appreciate any feedback :) Thanks !

### CODE REVIEW

**Comment by freak4pc** [comment]
I'm on develop and I did change the CHANGELOG, not sure what it's complaining about :)

**Comment by freak4pc** [comment]
It seems Danger is not letting this build. I'm not sure why ... Thoughts? @kzaher

**Comment by kzaher** [comment]
Hi @freak4pc ,

I think something other is messed up. Have you tried running `./scripts/all-tests.sh` locally?

**Comment by freak4pc** [comment]
Hey @kzaher , This seems weird:

```
» RxSwift ./scripts/all-tests.sh
RxSwift version: 3.3.1
Checking version for RxSwift
Checking version for RxCocoa
Checking version for RxBlocking
Checking version for RxTest
Plist versions aren't correct
```

🤔

**Comment by kzaher** [comment]
Hi @freak4pc ,

`git status` should report clean working tree. I'll make that script output more friendly message.

**Comment by freak4pc** [comment]
Thanks @kzaher
`git status` did show a clean working tree, But I thought my issue was related to the fact I pushed this PR based off of master instead of develop. I rebased on top of develop and still get the same `Plist versions aren't correct` error ... Any thoughts on how to debug that? 

Looking at the diff here in this PR I haven't changed anything that should be remotely related to a Plist.

**Comment by freak4pc** [comment]
All green now ! Had to rebuilt the SPM package and jazzy config. 
Feel free to merge when possible ! @kzaher

**Comment by blagh** [comment]
Late comment, but much thanks for this!

**Comment by freak4pc** [comment]
My pleasure 😇

**Pull request merged**
