### PR TITLE
Fixes deadlock with `shareReplayWhileLatest`. #1323

### PR DESCRIPTION
**Pull request by kzaher**
Hi @dpassage,

I think this should solve #1323 . Could you also verify that?

### CODE REVIEW

**Comment by freak4pc** [comment]
I can confirm, testing with @dpassage's example that this solves the Main Thread deadlock

**Comment by sergdort** [comment]
R.I.P `ShareReplay1 ` 😢

**Comment by freak4pc** [comment]
He was a brave warrior.

**Comment by dpassage** [comment]
Yes, fix works for me in the sample code; I'll try it in my production code later today. Thanks, @kzaher !

**Comment by dpassage** [comment]
Works in the production code, too!

I approve of this pull request.

seems legit

**Pull request merged**
