### PR TITLE
Fixs retryWhen logic

### PR DESCRIPTION
**Pull request by bontoJR**
This PR addresses the problem brought up with #1082. I know there's still a discussion to be made, but  in case the change is accepted, there's already a PR ready for that.

### CODE REVIEW

**Comment by kzaher** [comment]
I think this PR is an improvement of operator behavior, but I can't merge it before 4.0 since this would be a breaking change.

**Comment by bontoJR** [comment]
@kzaher absolutely right 👍

**Comment by freak4pc** [comment]
Even though this PR is very old, do we still want it in RxSwift 4 ? If so we can perhaps rebase this off the swift4 working branch and get it merged ? @bontoJR

**Comment by kzaher** [comment]
Hi, 

It seems to me that currently RxJava is the most popular implementation. As far as I can tell when error transformation block completes sequence doesn't terminate with latest error.

```java
Observable.just(0xf).concatWith(Observable.<Integer>error(new Throwable())).retryWhen(new Function<Observable<Throwable>, ObservableSource<?>>() {
            @Override
            public ObservableSource<?> apply(@NonNull Observable<Throwable> throwableObservable) throws Exception {
                return Observable.zip(throwableObservable, Observable.range(0, 3), new BiFunction<Throwable, Integer, Integer>() {
                    @Override
                    public Integer apply(@NonNull Throwable throwable, @NonNull Integer integer) throws Exception {
                        return integer;
                    }
                }).switchMap(new Function<Integer, ObservableSource<Long>>() {
                    @Override
                    public ObservableSource<Long> apply(@NonNull Integer o) throws Exception {
                        return Observable.timer(o.intValue() * 50, TimeUnit.MILLISECONDS, Schedulers.io());
                    }
                });
            }
        }).subscribe(new Consumer<Integer>() {
            @Override
            public void accept(@NonNull Integer integer) throws Exception {
                System.out.println(integer);
            }
        }, new Consumer<Throwable>() {
            @Override
            public void accept(@NonNull Throwable throwable) throws Exception {
                System.out.println(throwable);
            }
        }, new Action() {
            @Override
            public void run() throws Exception {
                System.out.println("Completed");
            }
        });
```

I kind of understand why that might be the case and since we are already consistent with RxJava it seems to me it might be better to leave the current behavior.

**Pull request closed without merging**
