### PR TITLE
[WIP] Implement auto loading example.

### PR DESCRIPTION
**Pull request by yoshinorisano**
This pull request adds an auto loading example discussed on https://github.com/ReactiveX/RxSwift/issues/170 .

### CODE REVIEW

**Comment by yoshinorisano** [comment]
@kzaher 
I've prepared the base implementation :)
Could you check it out?

**Comment by kzaher** [comment]
Hi @yoshinorisano ,

looks great so far. :+1:

Would you mind just adding a search box so we can also search those repositories?

If you could also do that, that would be awesome :)

**Comment by yoshinorisano** [comment]
@kzaher 
Thanks for checking my pull request!
I've added search bar and incremental search.
Please check them :)

**Comment by kzaher** [comment]
@yoshinorisano cool :+1:

Merging this ... I'm hoping I'll have time tomorrow to add those changes so we can future proof this question :)

**Comment by yoshinorisano** [comment]
@kzaher Thanks! I'm looking forward to it :)

**Pull request merged**
