### PR TITLE
Danger base setup

### PR DESCRIPTION
**Pull request by sergdort**
I've made made setup of `Danger`

Haven't find the way how to warn pull requests to master though :(

Tested on my fork 
screen shot 2016-06-03 at 10 38 54 am

I guess, I'll need to provide credentials for the bot to @kzaher ( or you can create your own :)  ),
The only one thing left is to add `DANGER_GITHUB_API_TOKEN` key and value to `Environment Variables` of `Travis`

### CODE REVIEW

**Comment by sergdort** [comment]
Hm... not sure why it's failing =)

**Comment by kzaher** [comment]
⚠️  Danger, danger .... ⚠️

**Comment by kzaher** [comment]
Hi @sergdort ,

I'm just curious, do you maybe know how much time this takes to run for each PR, and does it contain check for PR target branch?

```
$ bundle exec danger --verbose
bundler: failed to load command: danger (/Users/travis/build/ReactiveX/RxSwift/vendor/bundle/ruby/2.0.0/bin/danger)
```

Hm, yeah ... Looks like it's missing something.

**Comment by sergdort** [comment]
Hi, @kzaher yeh, there is `DANGER_GITHUB_API_TOKEN` key and value in Travis's `Environment Variables` missing
I can share with you credentials and token of my test bot, 
And, I was not able to find a setup for check for `master` branch :( . So I though may be some one who have experience with Danger would help us, may be @orta :)

**Comment by orta** [comment]
I've moved the token over to RxSwift's travis.

To determine the branch that it's being merged into, you can use this line: https://github.com/artsy/eigen/blob/master/Dangerfile#L78

**Comment by orta** [comment]
You probably want to change those references from `specs` to `Tests` in the `Dangerfile` too

**Comment by sergdort** [comment]
@orta  Thank you very much! 👍

**Pull request merged**
