### PR TITLE
Drive to signal intent that this is UI

### PR DESCRIPTION
**Pull request by seivan**
I am mostly asking if this would be accurate or correct.

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @seivan ,

I guess you could do something like this in this scenario also, but I'm not sure if it would bring much benefit since you can easily see that all properties are already satisfied since content offset can't fail and is already delivering elements on main thread.

**Comment by seivan** [comment]
But shouldn't it be a driver? I mean it's about intent if I understood the difference since both types jump on to main and won't error out(?) 
I'm genuinely curious as I'm Trying to grasp this and write a mini clone lazy monad just to get a better hang.

**Comment by kzaher** [comment]
Maybe you've meant to write something like
```
self.resultsTableView.rx_contentOffset.asDriver()
     .map { $0.x }
     .drive(self.leftPositionConstraint.rx_constant)
```

**Comment by seivan** [comment]
Yeah, heh, that looks much better and suggests I gotta do another run down.

**Pull request closed without merging**
