### PR TITLE
Add the UITextField reactive wrappers: UITextField Delegate

### PR DESCRIPTION
**Pull request by Nonchalant**
It extends the current implementation of the UITextField reactive wrapper adding the support for the delegate methods.

- `textFieldDidBeginEditing(_:)`
- `textFieldDidEndEditing(_:)`
- `textFieldShouldClear(_:)`
- `textFieldShouldReturn(_:)`

### CODE REVIEW

**Comment by kzaher** [comment]
Hi @Nonchalant ,

can you maybe provide some context? It seems to me that we already have first two events available through `rx.controlEvent` interface and the second two aren't events intended for observing, but customization part of UITextFieldDelegate interface.

**Comment by Nonchalant** [comment]
Hi @kzaher,

Thank you for your reply.

> It seems to me that we already have first two events available through rx.controlEvent interface

I agree completely. My provided interface is verbose and useless. I will remove it.

> the second two aren't events intended for observing, but customization part of UITextFieldDelegate interface

I wanna observe the events of the key event, but controlEvent cannot observe it. 
I have no idea about how to observe the events w/o UITextFieldDelegate. Please let me know.

Thank you.

**Comment by kzaher** [comment]
Hi @Nonchalant ,

which events would you like to observe?

**Comment by Nonchalant** [comment]
Hi @kzaher,

I wanna observer return key input in keyboard and clear key input in textField such as
```
textFieldShouldClear(_:)
textFieldShouldReturn(_:)
```

**Comment by kzaher** [comment]
Hi @Nonchalant ,

these aren't methods that are meant as a notification mechanism of UITextField but as a customization mechanism.

Trying to observe them usually means you are trying to do some hack.

If you want to observe when UITextField done button is pressed please use `.controlEvent(.editingDidEndOnExit)`.

**Comment by Nonchalant** [comment]
Hi @kzaher ,

Thank you for your reply.

I understand my mistake perfectly. I feel sorry for expending your precious time 🙇 
I use `.controlEvent(.editingDidEndOnExit)` and close this PR.

Thank you !!

**Pull request closed without merging**
